/**
 * Build helper for size rows on barista recipe cards.
 * @param {string} item
 * @param {string} oz16
 * @param {string} [oz20]
 */
export function b(item, oz16, oz20 = "") {
  return { item, oz16, oz20 };
}

/**
 * Weekly / archive specials — structured barista build sheets.
 * Source: 2026 WBC Specials Recipes.xlsx + current-week additions.
 *
 * Then: npm run seed:specials
 */

/** @typedef {{
 *   name: string,
 *   category: 'Coffee' | 'Matcha' | 'Refreshers',
 *   weekOf: string,
 *   weekLabel?: string,
 *   base?: string[],
 *   build?: { item: string, oz16: string, oz20?: string }[],
 *   toppings?: string[],
 *   method?: string[],
 *   notes?: string,
 * }} SpecialSeed */

/** @type {SpecialSeed[]} */
export const specialsSeed = [
  // ─── Coffee ───────────────────────────────────────────────
  {
    name: "Almond Croissant Latte",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Whole milk", "Double shot espresso"],
    build: [b("Vanilla", "1 pump", "1.5 pumps"), b("Brown sugar", "1 pump", "1.5 pumps")],
    toppings: ["Amaretto cold foam", "Sliced almonds"],
    method: ["Syrups in cup", "Add milk, ice, more milk", "Pull espresso on top", "Finish with foam + almonds"],
  },
  {
    name: "B & W Cookie Cloud",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Whole milk", "Espresso"],
    build: [b("Vanilla", "2 pumps", "3 pumps")],
    toppings: ["Chocolate fudge cold foam", "Cacao powder"],
    method: ["Vanilla + milk, mix, add ice", "Add espresso", "Top with chocolate fudge cold foam + cacao"],
  },
  {
    name: "Banana Brown Sugar Bliss",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk", "Double shot espresso"],
    build: [b("Brown sugar", "2 pumps", "3 pumps")],
    toppings: ["Banana bread cold foam", "Sweet plantain chip"],
    method: ["Syrup + milk, add ice", "Espresso", "Top with foam + plantain chip"],
  },
  {
    name: "Berry Blue Latte",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk", "Double shot espresso"],
    build: [b("Blueberry puree", "1 oz", "1.25 oz")],
    toppings: [],
    method: ["Puree + milk, mix", "Add ice, top with more milk", "Finish with double shot espresso"],
  },
  {
    name: "Berry Coco Cloud",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk", "Ice", "Double shot espresso"],
    build: [b("Coconut", "2 pumps", "3 pumps")],
    toppings: ["Strawberry cold foam"],
  },
  {
    name: "Berry Lavish Latte",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk", "Double shot espresso"],
    build: [
      b("Lavender", "1 pump", "2 pumps"),
      b("Blueberry puree", "0.5 oz", "1 oz"),
    ],
    toppings: [],
    method: ["Lavender + puree + milk, mix", "Add ice + more milk", "Top with double shot espresso"],
  },
  {
    name: "Blueberry Chai Pie",
    category: "Coffee",
    weekOf: "2026-08-17",
    weekLabel: "8/17",
    base: ["Milk"],
    build: [
      b("Blueberry puree", "1 oz", "1.2 oz"),
      b("Chai concentrate", "6 pumps", "8 pumps"),
    ],
    toppings: ["Vanilla cold foam", "Dust of cinnamon powder"],
    method: [
      "Blueberry + chai + milk, mix",
      "Add ice",
      "Top with vanilla cold foam",
      "Garnish with a dust of cinnamon powder",
    ],
  },
  {
    name: "Caramel Butter Cloud",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk", "Double shot espresso"],
    build: [b("Butter pecan", "2 pumps", "3 pumps")],
    toppings: ["Caramel cold foam", "Caramel drizzle"],
    method: ["Syrup + milk, mix", "Add ice + espresso", "Top with foam + drizzle"],
  },
  {
    name: "Caramel Cookie Cloud",
    category: "Coffee",
    weekOf: "2026-08-17",
    weekLabel: "8/17",
    base: ["Milk", "Ice", "Double shot espresso"],
    build: [b("Caramel", "2 pumps", "3 pumps")],
    toppings: [
      "Cookie butter cold foam",
      "Spiral caramel drizzle (small bottle)",
    ],
    method: [
      "Caramel + milk + ice",
      "Double shot espresso",
      "Top with cookie butter cold foam",
      "Garnish with spiral caramel drizzle",
    ],
  },
  {
    name: "Caramel Praline Macchiato",
    category: "Coffee",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    base: ["Whole milk", "Double shot espresso"],
    build: [b("Praline", "2 pumps", "3 pumps")],
    toppings: ["Caramel drizzle (inside cup)", "Caramel drizzle (finish)"],
    method: ["Caramel drizzle inside cup", "Praline + milk + ice", "Espresso on top", "Finish with caramel drizzle"],
  },
  {
    name: "Caramel Toffee Shaken Espresso",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Double shot espresso", "Oat milk"],
    build: [b("Toffee nut", "3 pumps", "4 pumps"), b("Cinnamon powder", "Pinch", "Pinch")],
    toppings: ["Caramel drizzle"],
    method: ["Shake syrup + cinnamon + espresso with ice", "Top with oat milk", "Caramel drizzle"],
  },
  {
    name: "Chocolate Banana Red Eye",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Drip coffee", "Double shot espresso"],
    build: [
      b("Dark chocolate (12 oz)", "1 pump", "—"),
      b("Banana bread (12 oz)", "1 pump", "—"),
      b("Dark chocolate (16 oz)", "1.5 pumps", "Same as 16 oz if iced"),
      b("Banana bread (16 oz)", "1.5 pumps", "Same as 16 oz if iced"),
    ],
    toppings: [],
    notes: "Iced: use the same measurements as the 16 oz hot recipe.",
  },
  {
    name: "Chocolate Irish Dream",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk", "Double shot espresso"],
    build: [b("Chocolate fudge", "1 pump", "2 pumps")],
    toppings: ["Irish cream cold foam", "Cocoa powder"],
    method: ["Syrup + milk, mix", "Add ice + more milk", "Espresso", "Top with foam + cocoa"],
  },
  {
    name: "Coco Mac Latte",
    category: "Coffee",
    weekOf: "2026-08-12",
    weekLabel: "8/12",
    base: ["Oat milk", "Double shot espresso"],
    build: [
      b("Macadamia", "1 pump", "2 pumps"),
      b("Coconut", "1 pump", "1 pump"),
    ],
    toppings: [],
  },
  {
    name: "Irish White Chocolate Latte",
    category: "Coffee",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    base: ["Whole milk", "Double shot espresso"],
    build: [b("Irish cream", "2 pumps", "3 pumps")],
    toppings: ["White chocolate drizzle (inside cup)", "Cacao powder"],
    method: [
      "White chocolate drizzle inside cup",
      "Irish cream + milk, mix, ice, more milk",
      "Espresso on top",
      "Dust with cacao powder",
    ],
  },
  {
    name: "Mango Spiced Cold Brew",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Cold brew", "Ice (to indent of cup)"],
    build: [],
    toppings: ["Mango cold foam", "Cinnamon powder"],
    notes: "Same build for 16 oz and 20 oz.",
  },
  {
    name: "Neapolitan Dream (Shaken Espresso)",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Espresso (in shaker)"],
    build: [
      b("Vanilla", "2 pumps", "2 pumps"),
      b("Chocolate fudge", "1 pump", "2 pumps"),
    ],
    toppings: ["Strawberry puree cold foam"],
    method: ["Syrups + espresso in shaker with ice", "Shake", "Top with strawberry puree cold foam"],
  },
  {
    name: "Pistachio Coco Shaken",
    category: "Coffee",
    weekOf: "2026-08-17",
    weekLabel: "8/17",
    base: ["Double shot espresso", "Splash of oat milk"],
    build: [
      b("Pistachio", "2 pumps", "3 pumps"),
      b("Chocolate fudge", "1 pump", "1 pump"),
    ],
    toppings: ["Cocoa powder"],
    method: [
      "Syrups + double shot espresso",
      "Shake with ice",
      "Finish with a splash of oat milk",
      "Garnish with cocoa powder",
    ],
  },
  {
    name: "Pistachio Oatmilk Shaken Espresso",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Espresso", "Oat milk"],
    build: [b("Pistachio", "2 pumps", "3 pumps")],
    toppings: [],
    method: ["Syrup + espresso, shake with ice", "Top with oat milk"],
  },
  {
    name: "Salted Brown Sugar Vanilla Shaken Espresso",
    category: "Coffee",
    weekOf: "2026-08-12",
    weekLabel: "8/12",
    base: ["Pinch of salt", "1 pump vanilla", "Double shot espresso", "Splash of milk of choice"],
    build: [b("Brown sugar", "2 pumps", "3 pumps")],
    toppings: [],
    method: ["Add syrups + salt + espresso", "Shake with ice", "Finish with splash of milk"],
  },
  {
    name: "Skinny Shaken Espresso",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Double shot espresso", "Skim milk"],
    build: [b("SF vanilla", "2 pumps", "3 pumps")],
    toppings: [],
    method: ["Syrup + espresso, shake with ice", "Finish with skim milk"],
  },
  {
    name: "Strawberry Coconut Latte",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk", "Double shot espresso"],
    build: [
      b("Coconut", "1 pump", "1.5 pumps"),
      b("Strawberry puree", "1 oz", "1.2 oz"),
    ],
    toppings: [],
    method: ["Coconut + puree + milk, mix", "Add ice + more milk", "Top with double shot espresso"],
  },
  {
    name: "Tiramisu Cookie Cloud",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk", "Ice", "Double shot espresso"],
    build: [b("Vanilla", "3 pumps", "4 pumps")],
    toppings: ["Tiramisu cold foam", "Oreo crumble"],
  },

  // ─── Matcha ───────────────────────────────────────────────
  {
    name: "BB Lavender Matcha",
    category: "Matcha",
    weekOf: "2026-08-17",
    weekLabel: "8/17",
    base: ["Milk", "Matcha"],
    build: [b("Lavender", "2 pumps", "3 pumps")],
    toppings: ["Blueberry cold foam", "Dust of matcha powder"],
    method: [
      "Lavender + milk, mix",
      "Add ice + matcha",
      "Top with blueberry cold foam",
      "Garnish with a dust of matcha powder",
    ],
  },
  {
    name: "Blooming Blue Matcha",
    category: "Matcha",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    base: ["2% milk"],
    build: [
      b("Elderflower", "3 pumps", "4 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Blueberry cold foam"],
    method: ["Syrup + matcha + milk, mix", "Add ice", "Top with blueberry cold foam"],
  },
  {
    name: "Blue Butterfly Dream",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk"],
    build: [
      b("Blueberry puree", "1 oz", "1.2 oz"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Coconut cold foam with butterfly pea tea (turns foam blue)"],
    method: ["Puree + milk, mix", "Add ice + matcha", "Top with coconut cold foam + butterfly pea tea"],
  },
  {
    name: "Blue Lychee Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["2% milk"],
    build: [
      b("Blueberry puree", "1 oz", "1.2 oz"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Lychee cold foam", "Blueberry puree garnish (squeeze bottle)"],
    method: ["Puree + milk, mix", "Add ice + matcha", "Top with lychee cold foam + blueberry garnish"],
  },
  {
    name: "Blueberry Matcha Lemonade",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Lemonade"],
    build: [
      b("Blueberry puree", "1 oz", "1.2 oz"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: [],
    method: ["Puree + lemonade, mix", "Add ice + more lemonade", "Top with matcha"],
  },
  {
    name: "Brown Sugar Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Oat milk"],
    build: [
      b("Brown sugar", "2 pumps", "3 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Vanilla cold foam", "Cinnamon powder"],
    method: ["Syrup + matcha + oat milk, mix", "Add ice", "Top with foam + cinnamon"],
  },
  {
    name: "Elderflower Oat Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Oat milk"],
    build: [
      b("Elderflower", "2 pumps", "3 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: [],
    method: ["Syrup + oat milk, mix", "Add ice + more milk", "Top with matcha"],
  },
  {
    name: "Guava Matcha Cloud",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk"],
    build: [
      b("Vanilla", "2 pumps", "3 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Guava juice cold foam"],
    method: ["Vanilla + milk + ice", "Add matcha", "Top with guava cold foam"],
  },
  {
    name: "L'Orange Vanilla Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Whole milk"],
    build: [
      b("Vanilla", "2 pumps", "3 pumps"),
      b("Orange extract", "5 drops", "8 drops"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: [],
    method: ["Vanilla + orange extract + milk, mix", "Add ice", "Top with matcha"],
  },
  {
    name: "Lavender Bliss Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk"],
    build: [
      b("Elderflower", "3 pumps", "4 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Lavender cold foam"],
    method: ["Syrup + matcha + milk, mix", "Add ice + more milk", "Top with lavender cold foam"],
  },
  {
    name: "Lychee & Cream Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["2% milk"],
    build: [
      b("Lychee", "3 pumps", "4 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Lychee cold foam"],
    method: ["Lychee + matcha + milk, mix", "Add ice", "Top with lychee cold foam"],
  },
  {
    name: "Lychee Coconut Cloud",
    category: "Matcha",
    weekOf: "2026-08-12",
    weekLabel: "8/12",
    base: ["Milk", "Matcha"],
    build: [b("Lychee", "2 pumps", "3 pumps")],
    toppings: ["Coconut cold foam", "Matcha powder garnish"],
  },
  {
    name: "Macadamia Matcha Cloud",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk"],
    build: [
      b("Macadamia", "2 pumps", "3 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Vanilla cold foam", "Cinnamon powder"],
    method: ["Syrup + matcha + milk, mix", "Add ice + more milk", "Top with foam + cinnamon"],
  },
  {
    name: "Mango Passion Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk"],
    build: [
      b("Mango puree", "1 oz", "1.2 oz"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Passion fruit puree cold foam", "2 dried orange slices"],
    method: ["Mango puree + milk + ice", "Add matcha", "Top with foam + orange slices"],
  },
  {
    name: "Muz Matcha Latte",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Milk"],
    build: [
      b("Banana bread", "2 pumps", "3 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["2 sweet plantain chips"],
    method: ["Syrup + milk + ice", "Top with matcha + plantain chips"],
  },
  {
    name: "Pistachio Cloud Matcha",
    category: "Matcha",
    weekOf: "2026-08-12",
    weekLabel: "8/12",
    base: ["Milk", "Matcha"],
    build: [b("Vanilla", "2 pumps", "3 pumps")],
    toppings: ["Pistachio cold foam"],
  },
  {
    name: "Strawberry Matcha Lemonade",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Lemonade"],
    build: [
      b("Strawberry puree", "1 oz", "1.2 oz"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: [],
    method: ["Puree + lemonade, mix", "Add ice + more lemonade", "Top with matcha"],
  },
  {
    name: "Ube Matcha Lemonade",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Lemonade"],
    build: [
      b("Ube", "3 pumps", "4 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: [],
    method: ["Ube + lemonade, mix", "Add ice + more lemonade", "Top with matcha"],
  },
  {
    name: "Vanilla Cookie Matcha",
    category: "Matcha",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    base: ["2% milk"],
    build: [
      b("Vanilla", "2 pumps", "3 pumps"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: ["Cookie butter cold foam", "Biscoff crumble"],
    method: ["Vanilla + matcha + milk, mix", "Add ice + more milk", "Top with foam + Biscoff crumble"],
  },
  {
    name: "Wild Passion Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["2% milk"],
    build: [b("Matcha", "1.2 oz", "1.5 oz")],
    toppings: ["Passion fruit puree cold foam", "Edible flower"],
    method: ["Matcha + milk, mix", "Add ice", "Top with foam + edible flower"],
  },

  // ─── Refreshers ───────────────────────────────────────────
  {
    name: "Citrus Sunset Matcha",
    category: "Refreshers",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    base: ["Lemonade"],
    build: [
      b("Passion fruit puree", "1 oz", "1.2 oz"),
      b("Matcha", "1.2 oz", "1.5 oz"),
    ],
    toppings: [],
    method: ["Puree + lemonade, mix", "Add ice + more lemonade", "Top with matcha"],
  },
  {
    name: "Lavender Eclipse Refresher",
    category: "Refreshers",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Lemonade"],
    build: [b("Lavender", "2 pumps", "3 pumps")],
    toppings: ["Butterfly pea tea"],
    method: ["Lavender + lemonade, mix", "Add ice + more lemonade", "Top with butterfly pea tea"],
  },
  {
    name: "Mango Butterfly Tea",
    category: "Refreshers",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    base: ["Lemonade"],
    build: [b("Mango puree", "1 oz", "1.2 oz")],
    toppings: ["Butterfly pea tea"],
    method: ["Mango puree + lemonade, mix", "Add ice + more lemonade", "Top with butterfly pea tea"],
  },
];

/** Build flattened search text from a structured special. */
export function buildSearchText(item) {
  const parts = [
    item.name,
    item.category,
    item.weekLabel,
    ...(item.base || []),
    ...(item.toppings || []),
    ...(item.method || []),
    item.notes || "",
    ...(item.build || []).flatMap((line) => [line.item, line.oz16, line.oz20]),
  ];
  return parts.filter(Boolean).join(" ").toLowerCase();
}
