/**
 * Menu Items Seed Data - Updated from Clover CSV Export
 * This file contains the exact menu items, prices, descriptions, and modifier group mappings
 * from the Clover POS system.
 */

export const menuItemsFromCSV = [
  // Coffee & Espresso (Espresso Bar)
  {
    name: "Americano",
    description: "Espresso shot filled with hot water for a smooth finish.",
    price: 3.6,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/AmericanoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (12-16)",
      "Extra Single Shots (Hot)",
    ],
  },
  {
    name: "Cappuccino",
    description: "Espresso with equal parts steamed milk and foam.",
    price: 4.55,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "foam"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/CappuccinoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Cup Size (12-16)",
      "Extra Single Shots (Hot)",
      "Milk Choice",
    ],
  },
  {
    name: "Doppio",
    description: "A bold double shot of espresso.",
    price: 3.25,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/DoppioLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Shot Preference", "Extra Single Shots (Hot)"],
  },
  {
    name: "Espresso",
    description: "1 oz espresso shot made with freshly roasted beans.",
    price: 2.85,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/EspressoLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Shot Preference", "Extra Single Shots (Hot)"],
  },
  {
    name: "Flat White",
    description: "Espresso with velvety, lightly textured milk.",
    price: 5.15,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "milk"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/LatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Cup Size (12-16)",
      "Extra Single Shots (Hot)",
      "Milk Choice",
    ],
  },
  {
    name: "Latte",
    description: "Espresso with steamed milk and a light milk crema.",
    price: 4.55,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "milk"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/LatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (12-16)",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Milk Choice",
      "Extra Single Shots (Hot)",
    ],
  },
  {
    name: "Mocha",
    description: "Espresso blended with chocolate and steamed milk.",
    price: 5.15,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "chocolate"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/MochaLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Cup Size (12-16)",
      "Extra Single Shots (Hot)",
      "Milk Choice",
    ],
  },
  {
    name: "Espresso Macchiato",
    description: "Espresso marked with a small amount of foam.",
    price: 5.15,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/EspressoMacchiatoLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Shot Preference", "Extra Single Shots (Hot)"],
  },
  {
    name: "Caramel Macchiato",
    description: "Layered espresso and milk with caramel.",
    price: 5.5,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "caramel"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (12-16)",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Milk Choice",
      "Extra Single Shots (Hot)",
    ],
  },
  {
    name: "Filtered Coffee",
    description: "Fresh filtered coffee. Select your cup size.",
    price: 2.55,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "coffee"],
    allergens: [],
    image: "/images/menu/Coffee/RegularCoffeeLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Cup Size (12-16)"],
  },

  // Cold Coffee
  {
    name: "Cold Brew",
    description: "Slow-steeped cold brew for a smooth, rich taste.",
    price: 4.65,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "coffee", "cold"],
    allergens: [],
    image: "/images/menu/Coffee/IcedAmericanoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Brew Cup Size (16-20)",
      "Ice Level",
      "Milk Choice",
      "Cold Foam",
      "Syrup Pumps (+$0.25 each)",
    ],
  },
  {
    name: "Iced Americano",
    description: "Espresso and cold water served over ice.",
    price: 3.95,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: [],
    image: "/images/menu/Coffee/IcedAmericanoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Ice Level",
      "Cold Foam",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Iced Caramel Macchiato",
    description: "Layered espresso and milk served over ice.",
    price: 5.95,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedCaramelMacchiatoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Cold Foam",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Iced Latte",
    description: "Espresso with cold milk poured over ice.",
    price: 4.65,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Cold Foam",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Iced Flat White",
    description: "Flat white served over ice.",
    price: 4.85,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedFlatWhiteLand.png",
    available: true,
    active: false,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Cold Foam",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Iced Mocha",
    description: "Mocha served over ice.",
    price: 5.85,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "chocolate", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedMochaLand.png",
    available: true,
    active: false,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Cold Foam",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Brown Sugar Cinnamon Shaken Espresso",
    description:
      "Double espresso shaken with ice, brown sugar, and cinnamon, finished with your choice of milk.",
    price: 5.15,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold", "shaken"],
    allergens: ["Dairy"],
    image: "", // UI shows "Photo coming soon"
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Cold Foam",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Caramel Shaken Espresso",
    description:
      "Double espresso shaken with ice and caramel, finished with your choice of milk.",
    price: 5.95,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold", "shaken", "caramel"],
    allergens: ["Dairy"],
    image: "", // UI shows "Photo coming soon"
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Cold Foam",
      "Extra Single Shots (Iced)",
    ],
  },

  // Smoothies
  {
    name: "Green Glow",
    description:
      "Spinach, kale, banana, avocado, chia seeds, milk, honey",
    price: 7.99,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "green"],
    allergens: ["Dairy"],
    image: "/images/menu/Smoothies/GreenGlowLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Smoothie Size",
      "Smoothie Add-Ons",
    ],
  },
  {
    name: "Triple B",
    description:
      "Strawberry, blueberry, raspberry, yogurt, milk.",
    price: 8.2,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "berry"],
    allergens: ["Dairy"],
    image: "/images/menu/Smoothies/BerryBoostLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Smoothie Size",
      "Smoothie Add-Ons",
    ],
  },
  {
    name: "Tropical Bliss",
    description:
      "Mango, pineapple, banana, orange juice, coconut, lime.",
    price: 7.5,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "tropical"],
    allergens: ["Coconut", "Dairy"],
    image: "/images/menu/Smoothies/TropicalBlissLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Smoothie Size", "Smoothie Add-Ons"],
  },
  {
    name: "Guava Cream",
    description: "Guava, Strawberry, Banana, Yogurt, Lime. Contains: Dairy.",
    price: 7.75,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "tropical", "guava"],
    allergens: ["Dairy"],
    image: "/images/menu/Smoothies/GuavaCreamLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Smoothie Size",
      "Smoothie Add-Ons",
    ],
  },
  {
    name: "Berry Mango Tango",
    description:
      "Strawberry, mango, vanilla protein, yogurt, honey, almond milk.",
    price: 9.25,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "protein", "berry", "mango"],
    allergens: ["Dairy", "Tree Nuts"],
    image: "", // Placeholder: no image yet; UI shows "Photo coming soon"
    available: true,
    active: true,
    modifierGroupNames: [
      "Smoothie Size",
      "Protein Powder",
      "Smoothie Add-Ons",
    ],
  },
  {
    name: "Power Couple",
    description:
      "Chia seed pudding, Vanilla protein, avocado, no-fat greek yogurt, peanut butter, honey.",
    price: 9.5,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "protein", "chia"],
    allergens: ["Peanuts", "Tree Nuts", "Dairy"],
    image: "", // Placeholder: no image yet; UI shows "Photo coming soon"
    available: true,
    active: true,
    modifierGroupNames: [
      "Smoothie Size",
      "Protein Powder",
      "Smoothie Add-Ons",
    ],
  },

  // Wild Bowl (build-your-own and predetermined bowls)
  {
    name: "Build Your Own Bowl",
    description:
      "1 base, 2 fruits, up to 8 toppings & 2 drizzles. Small / Medium +$1.",
    price: 9.99,
    currency: "USD",
    section: "Wild Bowl",
    tags: ["bowl", "custom", "healthy", "breakfast", "build your own"],
    allergens: [],
    image: "/images/menu/Oatmeals/NutFree.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Base",
      "Bowl Size",
      "Toppings",
      "Drizzels",
      "Fruit Toppings",
      "Extra Add-Ons",
    ],
  },
  {
    name: "Wild Vegan",
    description:
      "Chia Seed Pudding, Granola, Coconut Flakes, Almonds, Dried Cranberries, Peanut Butter, Honey, Strawberries, Bananas. You may remove or add toppings; rules: 1 base, 2 fruits, up to 8 toppings & 2 drizzles.",
    price: 9.99,
    currency: "USD",
    section: "Wild Bowl",
    tags: ["bowl", "healthy", "breakfast", "vegan"],
    allergens: [],
    image: "/images/menu/Oatmeals/WildVegan.png",
    available: true,
    active: true,
    // Same groups as Signature Bowl except base: use "Wild Vegan Base" (chia only; matches seedModifierGroups + CustomizationModal).
    modifierGroupNames: [
      "Wild Vegan Base",
      "Bowl Size",
      "Toppings",
      "Drizzels",
      "Fruit Toppings",
      "Extra Add-Ons",
    ],
  },
  {
    name: "Signature Bowl",
    description:
      "½ Chia Seed Pudding, ½ Yogurt, Granola, Pecans, Sunflower Seeds, Coconut Flakes, Peanut Butter, Honey, Strawberries, Blueberries. You may remove or add toppings; rules: 1 base, 2 fruits, up to 8 toppings & 2 drizzles.",
    price: 9.99,
    currency: "USD",
    section: "Wild Bowl",
    tags: ["bowl", "healthy", "breakfast", "signature"],
    allergens: ["Dairy"],
    image: "/images/menu/Oatmeals/WildVegan.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Base",
      "Bowl Size",
      "Toppings",
      "Drizzels",
      "Fruit Toppings",
      "Extra Add-Ons",
    ],
  },

  // Bakery & Pastries
  {
    name: "Plain Croissant",
    description:
      "Handcrafted with 12 layers of high-quality butter, creating a fluffy, flaky, and artisanally buttery experience. Freshly baked throughout the day. Contains: Wheat, milk, egg.",
    price: 4.5,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "croissant"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "/images/menu/Bakery/PlainCroissant.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Chocolate Croissant",
    description:
      'Traditional "pain au chocolat" with dark chocolate sticks rolled into croissant dough for a rich chocolatey bite. Contains: Wheat, milk, egg, soy.',
    price: 4.75,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "croissant", "chocolate"],
    allergens: ["Gluten", "Dairy", "Eggs", "Soy"],
    image: "/images/menu/Bakery/ChocolateCroissant.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Almond Croissant",
    description:
      "A traditional croissant filled with homemade almond cream and topped with sliced almonds for a delightful crunch. Contains: wheat, milk, egg, almond.",
    price: 5.35,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "croissant", "almond"],
    allergens: ["Gluten", "Dairy", "Eggs", "Tree Nuts"],
    image: "/images/menu/Bakery/AlmondCroissant.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Blueberry Muffin",
    description:
      "Light and fluffy, brimming with sweet blueberries and topped with pearl sugar for a delightful crunch. Contains: Wheat, milk, egg.",
    price: 4.75,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "muffin", "berry"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "/images/menu/Bakery/BlueberryMuffin.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Kouign Amann",
    description:
      "From Brittany, France, this pastry layers rich dough with butter and sugar, finished with a delicate caramel shell for extra crunch. Contains: Wheat, egg, soy, milk.",
    price: 5.1,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "pastry", "kouign amann"],
    allergens: ["Gluten", "Dairy", "Eggs", "Soy"],
    image: "/images/menu/Bakery/KouignAmann.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Cannele",
    description:
      "Classic French pastry from Bordeaux with a caramelized crust and tender custard center. Contains: Wheat, milk, egg.",
    price: 3.75,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "pastry", "cannele"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "/images/menu/Bakery/Cannele.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Flourless Brownie (Gluten Free)",
    description:
      "Rich, fudgy chocolate brownie made without flour. Gluten free. Contains: Dairy, egg, soy.",
    price: 4.75,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "brownie", "gluten free", "chocolate"],
    allergens: ["Dairy", "Eggs", "Soy"],
    image: "/images/menu/Bakery/GlutenFreeBrownie.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Vegan Muffin",
    description:
      "Plant-based muffin, moist and delicious. Made without dairy or eggs. Contains: Wheat.",
    price: 4.75,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "muffin", "vegan"],
    allergens: ["Gluten"],
    image: "/images/menu/Bakery/VeganMuffin.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Apple Danish",
    description:
      "Flaky pastry filled with sweet cinnamon-spiced apple and topped with a delicate glaze. Contains: Wheat, milk, egg.",
    price: 5.1,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "danish", "apple"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Sweet Lemon Bread",
    description:
      "Sweet lemon quick bread with a hint of citrus. Contains: Wheat, milk, egg.",
    price: 4.75,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "bread", "lemon"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },

  // Tea
  {
    name: "Assorted Tea",
    description: "Choose from an assortion of teas",
    price: 3.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot"],
    allergens: [],
    image: "/images/menu/Favorites/AssortedTeasLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Tea Selection"],
  },
  {
    name: "Iced Tea",
    description: "Fresh-brewed tea served over ice.",
    price: 3.65,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced"],
    allergens: [],
    image: "/images/menu/Favorites/IcedTeaLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Tea Selection", "Cold Cup Size", "Ice Level"],
  },
  {
    name: "Chai Latte (Hot)",
    description: "Spiced chai blended with steamed milk.",
    price: 4.95,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot", "spiced"],
    allergens: [],
    image: "/images/menu/Favorites/ChaiLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Syrup Pumps (+$0.25 each)",
      "Cup Size (12-16)",
      "Milk Choice",
    ],
  },
  {
    name: "Matcha Latte (Hot)",
    description: "Matcha blended with steamed milk",
    price: 5.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot", "matcha"],
    allergens: [],
    image: "/images/menu/Favorites/MatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Hot Cup Size",
      "Milk Choice",
      "Syrup Pumps (+$0.25 each)",
    ],
  },
  {
    name: "Iced Chai Latte",
    description: "Spiced chai tea blended with steamed milk.",
    price: 5.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "spiced"],
    allergens: [],
    image: "/images/menu/Favorites/IcedChaiLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Ice Level",
      "Milk Choice",
    ],
  },
  {
    name: "Iced Matcha Latte",
    description: "Matcha blended with milk and shaken over ice",
    price: 5.45,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha"],
    allergens: [],
    image: "/images/menu/Favorites/IcedMatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Cup Size",
      "Syrup Pumps (+$0.25 each)",
      "Milk Choice",
      "Cold Foam",
      "Ice Level",
    ],
  },
  {
    name: "Iced Strawberry Matcha Latte",
    description: "Matcha with strawberry and milk, shaken over ice.",
    price: 6.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "strawberry"],
    allergens: ["Dairy"],
    image: "/images/menu/Favorites/StrawberryMatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Brew Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Milk Choice",
      "Cold Foam",
      "Ice Level",
    ],
  },
  {
    name: "Iced Blueberry Matcha Latte",
    description: "Matcha with blueberry and milk, shaken over ice.",
    price: 6.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "blueberry"],
    allergens: ["Dairy"],
    image: "/images/menu/Favorites/BlueberryMatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Brew Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Milk Choice",
      "Cold Foam",
      "Ice Level",
    ],
  },
  {
    name: "Iced Mango Matcha Latte",
    description: "Matcha with mango and milk, shaken over ice.",
    price: 6.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "mango"],
    allergens: ["Dairy"],
    image: "/images/menu/Favorites/MangoMatchaLatte.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Brew Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Milk Choice",
      "Cold Foam",
      "Ice Level",
    ],
  },
];
