/**
 * Weekly / archive specials recipes for staff lookup.
 * Generated from: 2026 WBC Specials Recipes.xlsx
 * Sheets: UPCOMING SPECIALS, COFFEE DRINKS, MATCHA DRINKS, REFRESHERS
 * (UNPOPULAR SPECIALS was empty; SYRUP FLAVORS skipped — not drink recipes)
 *
 * Re-import: node scripts/importSpecialsFromXlsx.js
 * Then: npm run seed:specials
 */

/** @typedef {{
 *   name: string,
 *   category: 'Coffee' | 'Matcha' | 'Refreshers',
 *   recipe16oz: string,
 *   recipe20oz?: string,
 *   weekOf: string,
 *   weekLabel?: string,
 *   notes?: string,
 * }} SpecialSeed */

/** @type {SpecialSeed[]} */
export const specialsSeed = [
  {
    name: "Almond Croissant Latte",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 PUMP VANILLA & 1 PUMP BROWN SUGAR SYRUP, WHOLE MILK, ADD ICE THEN MORE MILK, DOUBLE SHOT ESPRESSO, TOPPED WITH AMARETTO COLD FOAM AND SLICED ALMONDS",
    recipe20oz: "1.5 PUMP VANILLA, 1.5 PUMP BROWN SUGAR",
  },
  {
    name: "B & W Cookie Cloud",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS VANILLA, WHOLE MILK, MIX THEN ICE, ESPRESSO AND CHOCOLATE FUDGE COLD FOAM - TOPPED WITH CACAO POWDER",
    recipe20oz: "3 PUMPS VANILLA",
  },
  {
    name: "Banana Brown Sugar Bliss",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS BROWN SUGAR SYRUP, MILK THEN ICE, DOUBLE SHOT ESPRESSO, TOPPED WITH BANANA BREAD COLD FOAM AND SWEET PLANTAIN CHIP",
    recipe20oz: "3 PUMPS BROWN SUGAR FOR LATTE BASE",
  },
  {
    name: "Berry Blue Latte",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 OZ BLUEBERRY PUREE, ADD MILK THEN MIX, ADD ICE, TOP WITH MORE MILK, FINISHED WITH DUOBLE SHOT OF ESPRESSO",
    recipe20oz: "1.25 OZ BLUEBERRY PUREE",
  },
  {
    name: "Berry Coco Cloud",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS COCONUT, MILK AND ICE, DOUBLE SHOT ESPRESSO, TOPPED WITH STRAWBERRY COLD FOAM",
    recipe20oz: "3 PUMPS COCONUT",
  },
  {
    name: "Berry Lavish Latte",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 PUMP LAVENDER SYRUP, .50 OZ BLUEBERRY PUREE, ADD MILK AND MIX, ADD ICE AND MORE MILK, TOP WITH DOUBLE SHOT OF ESPRESSO",
    recipe20oz: "2 PUMP LAVENDER, 1 OZ BLUEBERRY PUREE",
  },
  {
    name: "Caramel Butter Cloud",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS BUTTER PECAN SYRUP, MILK THEN MIX, ADD ICE AND DOUBLE SHOT ESPRESSO, TOPPED WITH CARAMEL COLD FOAM AND CARAMEL DRIZZLE GARNISH",
    recipe20oz: "3 PUMPS BUTTER PECAN FOR LATTE BASE",
  },
  {
    name: "Caramel Praline Macchiato",
    category: "Coffee",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    recipe16oz: "CARAMEL DRIZZLE INSIDE OF CUP, 2 PUMPS PRALINE SYRUP, WHOLE MILK, ADD ICE, TOPPED WITH DOUBLE SHOT ESPRESSO AND CARAMEL DRIZZLE",
    recipe20oz: "3 PUMPS PRALINE SYRUP",
  },
  {
    name: "Caramel Toffee Shaken Espresso",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "3 PUMPS TOFFEE NUT SYRUP, CINNAMON POWDER, DOUBLE SHOT ESPRESSO, OAT MILK, TOPPED WITH CARAMEL DRIZZLE",
    recipe20oz: "4 PUMPS TOFFEE NUT SYRUP",
  },
  {
    name: "Chocolate Banana Red Eye",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz:
      "12 OZ - 1 PUMP DARK CHOCOLATE, 1 PUMP BANANA BREAD, DRIP COFFEE, DOUBLE SHOT ESPRESSO. 16 OZ - 1.5 DARK CHOCOLATE, 1.5 PUMP BANANA BREAD, DRIP COFFEE, DOUBLE SHOT ESPRESSO",
    recipe20oz: "IF THIS DRINK IS ICED - USE SAME MEASUREMENTS FOR 16 OZ HOT RECIPE",
  },
  {
    name: "Chocolate Irish Dream",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 PUMP CHOCOLATE FUDGE SYRUP, ADD MILK THEN MIX, ADD ICE AND MORE MILK, DOUBLE SHOT ESPRESSO, TOPPED WITH IRISH CREAM COLD FOAM AND COCOA POWDER",
    recipe20oz: "2 PUMPS CHOCOLATE FUDGE SYRUP",
  },
  {
    name: "Coco Mac Latte",
    category: "Coffee",
    weekOf: "2026-08-12",
    weekLabel: "8/12",
    recipe16oz:
      "1 pump macadamia + 1 pump coconut, oat milk, double shot espresso",
    recipe20oz: "2 pumps macadamia + 1 pump coconut (same build otherwise)",
  },
  {
    name: "Irish White Chocolate Latte",
    category: "Coffee",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    recipe16oz: "WHITE CHOCOLATE DRIZZLE INSIDE OF CUP, 2 PUMPS IRISH CREAM SYRUP, WHOLE MILK, MIX THEN ICE, ADD MILK TOPPED WITH DOUBLE SHOT ESPRESSO AND CACAO POWDER",
    recipe20oz: "3 PUMPS IRISH CREAM",
  },
  {
    name: "Mango Spiced Cold Brew",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "COLD BREW AND ICE TO INDENT OF CUP, TOPPED WITH MANGO COLD FOAM AND CINNAMON POWDER",
    recipe20oz: "COLD BREW AND ICE TO INDENT OF CUP, TOPPED WITH MANGO COLD FOAM AND CINNAMON POWDER",
  },
  {
    name: "Neapolitan Dream (Shaken Espresso)",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMP VANILLA, 1 PUMP CHOCOLATE FUDGE INTO SHAKER WITH ESPRESSO, TOPPED WITH STRAWBERRY PUREE COLD FOAM",
    recipe20oz: "2 PUMP VANILLA, 2 PUMPS CHOCOLATE FUDGE INTO SHAKER WTH ESPRESSO, TOPPED WITH STRAWBERRY PUREE COLD FOAM",
  },
  {
    name: "Pistachio Oatmilk Shaken Espresso",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS OF PISTACHIO SYRUP, ESPRESSO, SHAKE WITH ICE, OAT MILK",
    recipe20oz: "3 PUMPS PISTACHIO",
  },
  {
    name: "Salted Brown Sugar Vanilla Shaken Espresso",
    category: "Coffee",
    weekOf: "2026-08-12",
    weekLabel: "8/12",
    recipe16oz:
      "2 pumps brown sugar, pinch of salt, 1 pump vanilla, double shot espresso; shake with ice and finish with a splash of choice of milk",
    recipe20oz:
      "3 pumps brown sugar, pinch of salt, 1 pump vanilla, double shot espresso; shake with ice and finish with a splash of choice of milk",
  },
  {
    name: "Skinny Shaken Espresso",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS SF VANILLA, DOUBLE SHOT ESPRESSO, SHAKE AND USE SKIM MILK",
    recipe20oz: "3 PUMPS SF VANILLA",
  },
  {
    name: "Strawberry Coconut Latte",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 PUMP COCONUT, 1 OZ STRAWBERRY PUREE, ADD MILK THEN MIX, ADD ICE AND MORE MILK, TOP WITH DOUBLE SHOT ESPRESSO",
    recipe20oz: "1.5 PUMP COCONUT, 1.2 OZ STRAWBERRY PUREE",
  },
  {
    name: "Tiramisu Cookie Cloud",
    category: "Coffee",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "3 PUMPS VANILLA, MILK AND ICE, DOUBLE SHOT ESPRESSO, TOPPED WITH TIRAMISU COLD FOAM AND OREO CRUMBLE",
    recipe20oz: "4 PUMPS VANILLA SYRUP IN LATTE BASE",
  },
  {
    name: "Blooming Blue Matcha",
    category: "Matcha",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    recipe16oz: "3 PUMPS ELDERFLOWER SYRUP, 1.2 OZ MATCHA, 2% MILK, MIX THEN ADD ICE, TOPPED WITH BLUEBERRY COLD FOAM",
    recipe20oz: "4 PUMPS ELDERFLOWER, 1.5 OZ MATCHA",
  },
  {
    name: "Blue Butterfly Dream",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 OZ BLUEBERRY PUREE, ADD MILK AND MIX, ADD ICE, 1.2 OZ MATCHA, TOPPED WITH COCONUT COLD FOAM WITH BUTTERFLY PEA TEA TO TURN FOAM BLUE",
    recipe20oz: "1.2 OZ BLUEBERRY PUREE, 1.5 OZ MATCHA",
  },
  {
    name: "Blue Lychee Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 OZ BLUEBERRY PUREE, 2% MILK THEN MIX, ADD ICE AND 1.2 OZ MATCHA, TOP WITH LYCHEE COLD FOAM (BLUE GARNISH TOPPING???) Use blueberry puree in small decrotive squeeze bottle for Garnish",
    recipe20oz: "1.2 OZ BLUEBERRY PUREE, 1.5 OZ MATCHA",
  },
  {
    name: "Blueberry Matcha Lemonade",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 OZ BLUEBERRY PUREE, ADD LEMONADE AND MIX, ADD ICE AND MORE LEMONADE, TOP WITH 1.2 OZ MATCHA",
    recipe20oz: "1.2 OZ BLUEBERRY PUREE, 1.5 OZ MATCHA",
  },
  {
    name: "Brown Sugar Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS BROWN SUGAR SYRUP, 1.2 OZ MATCHA , OAT MILK AND MIX THEN ICE, TOPPED WITH VANILLA COLD FOAM AND CINNAMON POWDER",
    recipe20oz: "3 PUMPS BROWN SUGAR SYRUP, 1.5 OZ MATCHA",
  },
  {
    name: "Elderflower Oat Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS ELDERFLOWER SYRUP, OAT MILK, MIX THEN ADD ICE, MORE MILK THEN TOP WITH 1.2 OZ MATCHA",
    recipe20oz: "3 PUMPS ELDERFLOWER SYRUP, 1.5 OZ MATCHA",
  },
  {
    name: "Guava Matcha Cloud",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS VANILLA, ADD MILK AND ICE, 1.2 OZ MATCHA, TOPPED WITH GUAVA JUICE COLD FOAM",
    recipe20oz: "3 PUMPS VANILLA, 1.5 OZ MATCHA",
  },
  {
    name: "L'Orange Vanilla Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS VANILLA SYRUP, 5 DROPS ORANGE EXTRACT, ADD WHOLE MILK AND MIX, ADD ICE, TOP WITH 1.2 OZ MATCHA",
    recipe20oz: "3 PUMPS VANILLA, 8 DROPS ORANGE EXTRACT, 1.5 OZ MATCHA",
  },
  {
    name: "Lavender Bliss Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "3 PUMPS ELDERFLOWER SYRUP, 1.2 OZ MATCHA, ADD MILK THEN MIX, ADD ICE THEN MORE MILK, TOPPED WITH LAVENDER COLD FOAM",
    recipe20oz: "4 PUMPS ELDERFLOWER, 1.5 OZ MATCHA",
  },
  {
    name: "Lychee & Cream Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "3 PUMPS LYCHEE, 1.2 OZ MATCHA, 2% MILK AND MIX, ADD ICE, TOP WITH LYCHEE COLD FOAM",
    recipe20oz: "4 PUMPS LYCHEE, 1.5 OZ MATCHA",
  },
  {
    name: "Lychee Coconut Cloud",
    category: "Matcha",
    weekOf: "2026-08-12",
    weekLabel: "8/12",
    recipe16oz:
      "2 pumps lychee, milk, matcha, topped with coconut cold foam, garnish with matcha powder",
    recipe20oz:
      "3 pumps lychee, milk, matcha, topped with coconut cold foam, garnish with matcha powder",
  },
  {
    name: "Macadamia Matcha Cloud",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS MACADAMIA NUT SYRUP, 1.2 OZ MATCHA, MILK AND MIX, ADD ICE AND MORE MILK, TOPPED WITH VANILLA COLD FOAM AND CINNAMON POWDER",
    recipe20oz: "3 PUMPS MACADAMIA SYRUP, 1.5 OZ MATCHA",
  },
  {
    name: "Mango Passion Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 OZ MANGO PUREE, ADD MILK AND ICE, 1.2 OZ MATCHA, TOPPED WITH PASSION FRUIT PUREE COLD FOAM AND 2 DRIED ORANGE SLICES",
    recipe20oz: "1.2 OZ MANGO PUREE, 1.5 OZ MATCHA",
  },
  {
    name: "Pistachio Cloud Matcha",
    category: "Matcha",
    weekOf: "2026-08-12",
    weekLabel: "8/12",
    recipe16oz:
      "2 pumps vanilla, milk, matcha, topped with pistachio cold foam",
    recipe20oz:
      "3 pumps vanilla, milk, matcha, topped with pistachio cold foam",
  },
  {
    name: "Muz Matcha Latte",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS BANANA BREAD SYRUP, ADD MILK AND ICE, TOP WITH 1.2 OZ MATCHA AND 2 SWEET PLANTAIN CHIPS",
    recipe20oz: "3 PUMPS BANANA BREAD SYRUP, 1.5 OZ MATCHA",
  },
  {
    name: "Strawberry Matcha Lemonade",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 OZ STRAWBERRY PUREE, ADD LEMONADE AND MIX, ADD ICE AND MORE LEMONADE, TOP WITH 1.2 OZ MATCHA",
    recipe20oz: "1.2 OZ STRAWBERRY PUREE, 1.5 OZ MATCHA",
  },
  {
    name: "Ube Matcha Lemonade",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "3 PUMPS UBE SYRUP, LEMONADE, MIX THEN ADD ICE, MORE LEMONADE, TOP WITH 1.2 OZ MATCHA",
    recipe20oz: "4 PUMPS UBE, 1.5 OZ MATCHA",
  },
  {
    name: "Vanilla Cookie Matcha",
    category: "Matcha",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    recipe16oz: "2 PUMPS VANILLA, 1.2 OZ MATCHA, 2% MILK, MIX THEN ICE, MORE MILK, TOPPED WITH COOKIE BUTTER COLD FOAM AND BISCOFF CRUMBLE",
    recipe20oz: "3 PUMPS VANILLA, 1.5 OZ MATCHA",
  },
  {
    name: "Wild Passion Matcha",
    category: "Matcha",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1.2 OZ MATCHA, 2 % MILK, MIX AND ADD ICE, TOPPED WITH PASSION FRUIT PUREE COLD FOAM AND GARNISHED WITH EDIBLE FLOWER",
    recipe20oz: "1.5 OZ MATCHA",
  },
  {
    name: "Citrus Sunset Matcha",
    category: "Refreshers",
    weekOf: "2026-07-27",
    weekLabel: "7/27",
    recipe16oz: "1 OZ PASSION FRUIT PUREE, LEMONADE, MIX, ADD ICE, MORE LEMONADE, TOP WITH 1.2 OZ MATCHA",
    recipe20oz: "1.2 OZ PASSION FRUIT PUREE, 1.5 OZ MATCHA",
  },
  {
    name: "Lavender Eclipse Refresher",
    category: "Refreshers",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "2 PUMPS LAVENDER, LEMONADE, MIX THEN ADD ICE, MORE LEMONADE TOPPED WITH BUTTERFLY PEA TEA",
    recipe20oz: "3 PUMPS LAVENDER",
  },
  {
    name: "Mango Butterfly Tea",
    category: "Refreshers",
    weekOf: "2026-01-01",
    weekLabel: "Archive",
    recipe16oz: "1 OZ MANGO PUREE, LEMONADE THEN MIX, ADD ICE AND MORE LEMONADE, TOPPED WITH BUTTERFLY PEA TEA",
    recipe20oz: "1.2 OZ MANGO PUREE",
  },
];
