/**
 * Menu Items Seed Data - Updated from Clover CSV Export
 * This file contains the exact menu items, prices, descriptions, and modifier group mappings
 * from the Clover POS system.
 */

/** Extra Single Shots always immediately after Shot Preference. */
const HOT_LATTE_MODIFIERS = [
  "Shot Preference",
  "Extra Single Shots (Hot)",
  "Espresso Bean",
  "Cup Size (12-16)",
  "Syrup Pumps (+$0.25 each)",
  "Coffee Toppings",
  "Whipped Cream",
  "Milk Choice",
];

const RED_EYE_MODIFIERS = [
  "Shot Preference",
  "Extra Single Shots (Hot)",
  "Espresso Bean",
  "Cup Size (12-16) Red Eye",
  "Syrup Pumps (+$0.25 each)",
  "Coffee Toppings",
  "Whipped Cream",
  "Milk Choice",
];

const HOT_AMERICANO_MODIFIERS = [
  "Shot Preference",
  "Extra Single Shots (Hot)",
  "Espresso Bean",
  "Cup Size (12-16)",
];

const HOT_CAPPUCCINO_STYLE_MODIFIERS = [
  "Shot Preference",
  "Extra Single Shots (Hot)",
  "Espresso Bean",
  "Syrup Pumps (+$0.25 each)",
  "Coffee Toppings",
  "Whipped Cream",
  "Milk Choice",
];

const HOT_ESPRESSO_4OZ_MODIFIERS = [
  "Shot Preference",
  "Extra Single Shots (Hot)",
  "Espresso Bean",
];

const CORTADO_MODIFIERS = [...HOT_ESPRESSO_4OZ_MODIFIERS, "Milk Choice"];

const ICED_LATTE_MODIFIERS = [
  "Shot Preference",
  "Extra Single Shots (Iced)",
  "Espresso Bean",
  "Cup Size (16-20)",
  "Syrup Pumps (+$0.25 each)",
  "Coffee Toppings",
  "Whipped Cream",
  "Ice Level",
  "Milk Choice",
  "Cold Foam",
];

const ICED_AMERICANO_MODIFIERS = [
  "Shot Preference",
  "Extra Single Shots (Iced)",
  "Espresso Bean",
  "Cup Size (16-20)",
  "Ice Level",
  "Cold Foam",
];

const ICED_STRAWBERRY_MATCHA_MODIFIERS = [
  "Cold Brew Cup Size (16-20)",
  "Syrup Pumps (+$0.25 each)",
  "Milk Choice",
  "Cold Foam",
  "Ice Level",
];

const HOT_CHOCOLATE_MODIFIERS = ["Cup Size (12-16)", "Milk Choice"];

const LONDON_FOG_MODIFIERS = [
  "Hot Cup Size",
  "Milk Choice",
  "Syrup Pumps (+$0.25 each)",
];

export const menuItemsFromCSV = [
  // Coffee & Espresso (Espresso Bar)
  {
    name: "Americano",
    description: "Espresso shot filled with hot water for a smooth finish.",
    price: 3.8,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/AmericanoLand.png",
    available: true,
    active: true,
    modifierGroupNames: HOT_AMERICANO_MODIFIERS,
  },
  {
    name: "Cappuccino",
    description:
      "Served in a 12oz cup, filled to 8oz total: espresso with equal parts steamed milk and foam.",
    price: 4.7,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "foam"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/CappuccinoLand.png",
    available: true,
    active: true,
    modifierGroupNames: HOT_CAPPUCCINO_STYLE_MODIFIERS,
  },
  {
    name: "Doppio",
    description: "A bold double shot of espresso.",
    price: 3.4,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/DoppioLand.png",
    available: true,
    active: true,
    modifierGroupNames: HOT_ESPRESSO_4OZ_MODIFIERS,
  },
  {
    name: "Cortado",
    description:
      "Double shot of espresso with a small amount of steamed milk, served in a 4oz cup (whole milk by default).",
    price: 4.0,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: CORTADO_MODIFIERS,
  },
  {
    name: "Lungo",
    description:
      "A long-pull double shot of espresso for a milder, more voluminous 4oz cup.",
    price: 3.4,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: HOT_ESPRESSO_4OZ_MODIFIERS,
  },
  {
    name: "Espresso",
    description: "1 oz espresso shot made with freshly roasted beans.",
    price: 1.7,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/EspressoLand.png",
    available: true,
    active: true,
    modifierGroupNames: HOT_ESPRESSO_4OZ_MODIFIERS,
  },
  {
    name: "Flat White",
    description:
      "Served in a 12oz cup, filled to 8oz total: espresso with velvety, lightly textured milk.",
    price: 4.7,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "milk"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/LatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: HOT_CAPPUCCINO_STYLE_MODIFIERS,
  },
  {
    name: "Latte",
    description: "Espresso with steamed milk and a light milk crema.",
    price: 4.7,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "milk"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/LatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: HOT_LATTE_MODIFIERS,
  },
  {
    name: "Mocha",
    description: "Espresso blended with chocolate and steamed milk.",
    price: 5.8,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "chocolate"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/MochaLand.png",
    available: true,
    active: true,
    modifierGroupNames: HOT_LATTE_MODIFIERS,
  },
  {
    name: "Espresso Macchiato",
    description: "Espresso marked with a small amount of foam.",
    price: 4.2,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/EspressoMacchiatoLand.png",
    available: true,
    active: true,
    modifierGroupNames: HOT_ESPRESSO_4OZ_MODIFIERS,
  },
  {
    name: "Caramel Macchiato",
    description: "Layered espresso and milk with caramel.",
    price: 5.4,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "caramel"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/CaramelMacchiatoLand.png",
    available: true,
    active: true,
    modifierGroupNames: HOT_LATTE_MODIFIERS,
  },
  {
    name: "Spiced Honey Ritual",
    description:
      "Honey with vanilla, cinnamon, and drops of orange extract, served hot with a double shot of espresso and steamed milk (whole milk by default).",
    price: 5.7,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "honey", "specialty"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: HOT_LATTE_MODIFIERS,
  },
  {
    name: "Hot Chocolate",
    description:
      "Premium chocolate sauce with milk of your choice, served hot (whole milk by default).",
    price: 4.2,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "chocolate"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: HOT_CHOCOLATE_MODIFIERS,
  },
  {
    name: "Cafe Au Lait",
    description:
      "Drip coffee with steamed milk, served hot (whole milk by default).",
    price: 4.1,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "coffee", "milk"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: HOT_LATTE_MODIFIERS,
  },
  {
    name: "Red Eye",
    description:
      "Drip coffee with a double shot of espresso, served hot in 12oz or 16oz.",
    price: 5.2,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "coffee", "espresso"],
    allergens: [],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: RED_EYE_MODIFIERS,
  },
  {
    name: "Filtered Coffee",
    description: "Fresh filtered coffee. Select your cup size.",
    price: 3.1,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "coffee"],
    allergens: [],
    image: "/images/menu/Coffee/RegularCoffeeLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Cup Size (12-16)"],
  },

  // Cold Coffee
  {
    name: "Cold Brew",
    description: "Slow-steeped cold brew for a smooth, rich taste.",
    price: 4.8,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "coffee", "cold"],
    allergens: [],
    image: "/images/menu/Coffee/IcedAmericanoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Brew Cup Size (16-20)",
      "Ice Level",
      "Milk Choice",
      "Cold Foam",
      "Syrup Pumps (+$0.25 each)",
    ],
  },
  {
    name: "Iced Americano",
    description: "Espresso and cold water served over ice.",
    price: 3.9,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: [],
    image: "/images/menu/Coffee/IcedAmericanoLand.png",
    available: true,
    active: true,
    modifierGroupNames: ICED_AMERICANO_MODIFIERS,
  },
  {
    name: "Iced Caramel Macchiato",
    description: "Layered espresso and milk served over ice.",
    price: 6.2,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedCaramelMacchiatoLand.png",
    available: true,
    active: true,
    modifierGroupNames: ICED_LATTE_MODIFIERS,
  },
  {
    name: "Iced Latte",
    description: "Espresso with cold milk poured over ice.",
    price: 4.8,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: ICED_LATTE_MODIFIERS,
  },
  {
    name: "Iced Flat White",
    description: "Flat white served over ice.",
    price: 4.85,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedFlatWhiteLand.png",
    available: true,
    active: false,
    modifierGroupNames: ICED_LATTE_MODIFIERS,
  },
  {
    name: "Iced Mocha Latte",
    description:
      "Double shot of espresso with premium chocolate sauce and milk of your choice, served over ice (whole milk by default).",
    price: 6.1,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "chocolate", "cold"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: ICED_LATTE_MODIFIERS,
  },
  {
    name: "B-Berry White Chocolate Bloom",
    description:
      "Double shot of espresso over white chocolate and milk of your choice, topped with blueberry cold foam, served iced (whole milk by default).",
    price: 7.3,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold", "specialty"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: ICED_LATTE_MODIFIERS,
  },
  {
    name: "Shaken Ube Meadow",
    description:
      "Toasted marshmallow and ube over a double shot of espresso, shaken with ice; served 16–20oz with ube garnish (whole milk by default).",
    price: 6.5,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold", "shaken", "specialty"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: ICED_LATTE_MODIFIERS,
  },
  {
    name: "Brown Sugar Cinnamon Shaken Espresso",
    description:
      "Double espresso shaken with ice, brown sugar, and cinnamon, finished with your choice of milk.",
    price: 5.8,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold", "shaken"],
    allergens: ["Dairy"],
    image: "", // UI shows "Photo coming soon"
    available: true,
    active: true,
    modifierGroupNames: ICED_LATTE_MODIFIERS,
  },
  {
    name: "Caramel Shaken Espresso",
    description:
      "Double espresso shaken with ice and caramel, finished with your choice of milk.",
    price: 6.2,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold", "shaken", "caramel"],
    allergens: ["Dairy"],
    image: "", // UI shows "Photo coming soon"
    available: true,
    active: true,
    modifierGroupNames: ICED_LATTE_MODIFIERS,
  },

  // Smoothies
  {
    name: "Green Glow",
    description: "Spinach, kale, banana, avocado, chia seeds, milk, honey",
    price: 8.3,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "green"],
    allergens: ["Dairy"],
    image: "/images/menu/Smoothies/GreenGlowLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Smoothie Size", "Smoothie Add-Ons"],
  },
  {
    name: "Triple B",
    description: "Strawberry, blueberry, raspberry, yogurt, milk.",
    price: 8.5,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "berry"],
    allergens: ["Dairy"],
    image: "/images/menu/Smoothies/BerryBoostLand.png",
    available: false,
    active: false,
    modifierGroupNames: ["Smoothie Size", "Smoothie Add-Ons"],
  },
  {
    name: "Tropical Bliss",
    description: "Mango, pineapple, banana, orange juice, coconut, lime.",
    price: 7.8,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "tropical"],
    allergens: ["Coconut", "Dairy"],
    image: "/images/menu/Smoothies/TropicalBlissLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Smoothie Size", "Smoothie Add-Ons"],
  },
  {
    name: "Guava Cream",
    description: "Guava, Strawberry, Banana, Yogurt, Lime. Contains: Dairy.",
    price: 8,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "tropical", "guava"],
    allergens: ["Dairy"],
    image: "/images/menu/Smoothies/GuavaCreamLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Smoothie Size", "Smoothie Add-Ons"],
  },
  {
    name: "Berry Mango Tango",
    description:
      "Strawberry, mango, vanilla protein, yogurt, honey, almond milk.",
    price: 9.6,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "protein", "berry", "mango"],
    allergens: ["Dairy", "Tree Nuts"],
    image: "", // Placeholder: no image yet; UI shows "Photo coming soon"
    available: true,
    active: true,
    modifierGroupNames: ["Smoothie Size", "Protein Powder", "Smoothie Add-Ons"],
  },
  {
    name: "Power Couple",
    description:
      "Chia seed pudding, Vanilla protein, avocado, no-fat greek yogurt, peanut butter, honey.",
    price: 9.8,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "protein", "chia"],
    allergens: ["Peanuts", "Tree Nuts", "Dairy"],
    image: "", // Placeholder: no image yet; UI shows "Photo coming soon"
    available: true,
    active: true,
    modifierGroupNames: ["Smoothie Size", "Protein Powder", "Smoothie Add-Ons"],
  },

  // Wild Bowl (build-your-own and predetermined bowls)
  {
    name: "Build Your Own Bowl",
    description:
      "Choose your base and size. Add up to 8 toppings, 2 fruits, and 2 drizzles if you like. Medium +$1.",
    price: 10.3,
    currency: "USD",
    section: "Wild Bowl",
    tags: ["bowl", "custom", "healthy", "breakfast", "build your own"],
    allergens: [],
    image: "/images/menu/Oatmeals/NutFree.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Base",
      "Bowl Size",
      "Toppings (Build Your Own)",
      "Drizzels",
      "Fruit Toppings (Build Your Own)",
      "Extra Add-Ons",
    ],
  },
  {
    name: "Wild Vegan",
    description:
      "Chia Seed Pudding, Granola, Coconut Flakes, Almonds, Dried Cranberries, Peanut Butter, Honey, Strawberries, Bananas. You may remove or add toppings; rules: 1 base, 2 fruits, up to 8 toppings & 2 drizzles.",
    price: 10.3,
    currency: "USD",
    section: "Wild Bowl",
    tags: ["bowl", "healthy", "breakfast", "vegan"],
    allergens: [],
    image: "/images/menu/Oatmeals/WildVegan.png",
    available: true,
    active: true,
    // Same groups as Signature Bowl except base: use "Wild Vegan Base" (chia only; matches seedModifierGroups + CustomizationModal).
    modifierGroupNames: [
      "Wild Vegan Base",
      "Bowl Size",
      "Toppings",
      "Drizzels",
      "Fruit Toppings",
      "Extra Add-Ons",
    ],
  },
  {
    name: "Signature Bowl",
    description:
      "½ Chia Seed Pudding, ½ Yogurt, Granola, Pecans, Sunflower Seeds, Coconut Flakes, Peanut Butter, Honey, Strawberries, Blueberries. You may remove or add toppings; rules: 1 base, 2 fruits, up to 8 toppings & 2 drizzles.",
    price: 10.3,
    currency: "USD",
    section: "Wild Bowl",
    tags: ["bowl", "healthy", "breakfast", "signature"],
    allergens: ["Dairy"],
    image: "/images/menu/Oatmeals/WildVegan.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Base",
      "Bowl Size",
      "Toppings",
      "Drizzels",
      "Fruit Toppings",
      "Extra Add-Ons",
    ],
  },

  // Bakery & Pastries
  {
    name: "Plain Croissant",
    description:
      "Handcrafted with 12 layers of high-quality butter, creating a fluffy, flaky, and artisanally buttery experience. Freshly baked throughout the day. Contains: Wheat, milk, egg.",
    price: 4.7,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "croissant"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "/images/menu/Bakery/PlainCroissant.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Chocolate Croissant",
    description:
      'Traditional "pain au chocolat" with dark chocolate sticks rolled into croissant dough for a rich chocolatey bite. Contains: Wheat, milk, egg, soy.',
    price: 4.9,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "croissant", "chocolate"],
    allergens: ["Gluten", "Dairy", "Eggs", "Soy"],
    image: "/images/menu/Bakery/ChocolateCroissant.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Almond Croissant",
    description:
      "A traditional croissant filled with homemade almond cream and topped with sliced almonds for a delightful crunch. Contains: wheat, milk, egg, almond.",
    price: 5.6,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "croissant", "almond"],
    allergens: ["Gluten", "Dairy", "Eggs", "Tree Nuts"],
    image: "/images/menu/Bakery/AlmondCroissant.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Blueberry Muffin",
    description:
      "Light and fluffy, brimming with sweet blueberries and topped with pearl sugar for a delightful crunch. Contains: Wheat, milk, egg.",
    price: 4.9,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "muffin", "berry"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "/images/menu/Bakery/BlueberryMuffin.png",
    available: false,
    active: false,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Kouign Amann",
    description:
      "From Brittany, France, this pastry layers rich dough with butter and sugar, finished with a delicate caramel shell for extra crunch. Contains: Wheat, egg, soy, milk.",
    price: 5.3,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "pastry", "kouign amann"],
    allergens: ["Gluten", "Dairy", "Eggs", "Soy"],
    image: "/images/menu/Bakery/KouignAmann.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Cannele",
    description:
      "Classic French pastry from Bordeaux with a caramelized crust and tender custard center. Contains: Wheat, milk, egg.",
    price: 3.9,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "pastry", "cannele"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "/images/menu/Bakery/Cannele.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Flourless Brownie (Gluten Free)",
    description:
      "Rich, fudgy chocolate brownie made without flour. Gluten free. Contains: Dairy, egg, soy.",
    price: 4.9,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "brownie", "gluten free", "chocolate"],
    allergens: ["Dairy", "Eggs", "Soy"],
    image: "/images/menu/Bakery/GlutenFreeBrownie.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Vegan Muffin",
    description:
      "Plant-based muffin, moist and delicious. Made without dairy or eggs. Contains: Wheat.",
    price: 4.9,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "muffin", "vegan"],
    allergens: ["Gluten"],
    image: "/images/menu/Bakery/VeganMuffin.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Apple Danish",
    description:
      "Flaky pastry filled with sweet cinnamon-spiced apple and topped with a delicate glaze. Contains: Wheat, milk, egg.",
    price: 5.3,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "danish", "apple"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Sweet Lemon Bread",
    description:
      "Sweet lemon quick bread with a hint of citrus. Contains: Wheat, milk, egg.",
    price: 4.9,
    currency: "USD",
    section: "Bakery & Pastries",
    onlineOrderable: false,
    tags: ["bakery", "bread", "lemon"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    image: "",
    available: false,
    active: false,
    modifierGroupNames: ["Warmed"],
  },

  // Tea
  {
    name: "Assorted Tea",
    description: "Choose from an assortion of teas",
    price: 3.4,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot"],
    allergens: [],
    image: "/images/menu/Favorites/AssortedTeasLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Tea Selection"],
  },
  {
    name: "Iced Unsweetened Tea",
    description: "Unsweetened tea served over ice. Add syrups if desired.",
    price: 3.8,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "unsweetened"],
    allergens: [],
    image: "/images/menu/Favorites/IcedTeaLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Cup Size",
      "Ice Level",
      "Syrup Pumps (+$0.25 each)",
    ],
  },
  {
    name: "Chai Latte (Hot)",
    description: "Spiced chai blended with steamed milk.",
    price: 5.1,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot", "spiced"],
    allergens: [],
    image: "/images/menu/Favorites/ChaiLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Syrup Pumps (+$0.25 each)",
      "Cup Size (12-16)",
      "Milk Choice",
    ],
  },
  {
    name: "Matcha Latte (Hot)",
    description: "Matcha blended with steamed milk",
    price: 5.5,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot", "matcha"],
    allergens: [],
    image: "/images/menu/Favorites/MatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Hot Cup Size",
      "Milk Choice",
      "Syrup Pumps (+$0.25 each)",
    ],
  },
  {
    name: "London Fog",
    description:
      "Earl grey with steamed milk and vanilla, topped with a dust of cinnamon, served hot.",
    price: 5.1,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot", "earl grey"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: LONDON_FOG_MODIFIERS,
  },
  {
    name: "Iced Chai Latte",
    description: "Spiced chai tea blended with steamed milk.",
    price: 5.5,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "spiced"],
    allergens: [],
    image: "/images/menu/Favorites/IcedChaiLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.25 each)",
      "Ice Level",
      "Milk Choice",
    ],
  },
  {
    name: "Iced Matcha Latte",
    description: "Matcha blended with milk and shaken over ice",
    price: 5.7,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha"],
    allergens: [],
    image: "/images/menu/Favorites/IcedMatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Cup Size",
      "Syrup Pumps (+$0.25 each)",
      "Milk Choice",
      "Cold Foam",
      "Ice Level",
    ],
  },
  {
    name: "Iced Strawberry Matcha Latte",
    description: "Matcha with strawberry and milk, shaken over ice.",
    price: 6.5,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "strawberry"],
    allergens: ["Dairy"],
    image: "/images/menu/Favorites/StrawberryMatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: ICED_STRAWBERRY_MATCHA_MODIFIERS,
  },
  {
    name: "Iced Blueberry Matcha Latte",
    description: "Matcha with blueberry and milk, shaken over ice.",
    price: 6.5,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "blueberry"],
    allergens: ["Dairy"],
    image: "/images/menu/Favorites/BlueberryMatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: ICED_STRAWBERRY_MATCHA_MODIFIERS,
  },
  {
    name: "Iced Mango Matcha Latte",
    description: "Matcha with mango and milk, shaken over ice.",
    price: 6.5,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "mango"],
    allergens: ["Dairy"],
    image: "/images/menu/Favorites/MangoMatchaLatte.png",
    available: true,
    active: true,
    modifierGroupNames: ICED_STRAWBERRY_MATCHA_MODIFIERS,
  },
  {
    name: "Ube Matcha Lemonade",
    description:
      "Lemonade mixed with ube over ice, topped with matcha (2% milk by default when milk is selected).",
    price: 6.5,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "ube", "lemonade"],
    allergens: ["Dairy"],
    image: "",
    available: true,
    active: true,
    modifierGroupNames: ICED_STRAWBERRY_MATCHA_MODIFIERS,
  },
];
