// Modifier Groups Seed Data
// Based on Clover POS export analysis - Updated with exact options and pricing

export const modifierGroups = [
  {
    name: "Shot Preference",
    description: "Choose your espresso shot preference",
    type: "single",
    required: false,
    options: [
      { name: "Single Shot (instead of double)", price: 0, available: true },
    ],
  },
  {
    name: "Espresso Bean",
    displayName: "Regular, Decaf, or Half-Caf",
    description: "Regular espresso, decaf, or half-caf",
    type: "single",
    required: true,
    options: [
      { name: "Regular", price: 0, available: true },
      { name: "Decaf", price: 0, available: true },
      { name: "Half-Caf", price: 0, available: true },
    ],
  },
  {
    name: "Cup Size (12-16)",
    description: "Select your cup size",
    type: "single",
    required: true,
    options: [
      { name: "Small (12oz)", price: 0, available: true },
      { name: "Medium (16oz)", price: 0.6, available: true },
      { name: "Large (20oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Cup Size (12-16) Red Eye",
    displayName: "Cup Size (12-16)",
    description: "Select your cup size. Medium (16oz) is +$0.30.",
    type: "single",
    required: true,
    options: [
      { name: "Small (12oz)", price: 0, available: true },
      { name: "Medium (16oz)", price: 0.3, available: true },
      { name: "Large (20oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Cup Size (16-20)",
    description: "Select your cup size",
    type: "single",
    required: true,
    options: [
      { name: "Medium (16oz)", price: 0, available: true },
      { name: "Large (20oz)", price: 0.8, available: true },
      { name: "Small (12oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Cold Brew Cup Size (16-20)",
    displayName: "Cup Size (16-20)",
    description: "Select your cup size",
    type: "single",
    required: true,
    options: [
      { name: "Medium (16oz)", price: 0, available: true },
      { name: "Large (20oz)", price: 0.8, available: true },
      { name: "Small (12oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Hot Cup Size",
    description: "Select your hot cup size",
    type: "single",
    required: true,
    options: [
      { name: "Small (12oz)", price: 0, available: true },
      { name: "Medium (16oz)", price: 0.6, available: true },
      { name: "Large (20oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Cold Cup Size",
    description: "Select your cold cup size",
    type: "single",
    required: true,
    options: [
      { name: "Medium (16oz)", price: 0, available: true },
      { name: "Large (20oz)", price: 0.8, available: true },
      { name: "Small (12oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Smoothie Size",
    description: "Smoothies are served in a standard 16oz cup.",
    type: "single",
    required: true,
    options: [
      { name: "16oz", price: 0, available: true },
    ],
  },
  {
    name: "Protein Powder",
    description: "Add vanilla protein to your smoothie.",
    type: "single",
    required: false,
    options: [
      { name: "Vanilla Mass protein powder", price: 0, available: true },
    ],
  },
  {
    name: "Syrup Pumps (+$0.25 each)",
    displayName: "Syrups & sweeteners",
    description:
      "Add syrup, puree, or sweetener. Price per pump is shown ($0.30, $0.50, or $0.60).",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 6,
    options: [
      { name: "Banana Bread Syrup pump", price: 0.3, available: true },
      { name: "Blueberry puree", price: 0.6, available: true },
      { name: "Brown Sugar Cin Syrup Pump", price: 0.5, available: true },
      { name: "Caramel Single Pump", price: 0.3, available: true },
      { name: "Chocolate Single pump", price: 0.6, available: true },
      { name: "Cinnamon Single Pump", price: 0.3, available: true },
      { name: "Coconut Single Pump", price: 0.3, available: true },
      { name: "Cookie Butter Single Pump", price: 0.5, available: true },
      { name: "Hazelnut Single Pump", price: 0.3, available: true },
      { name: "Honey", price: 0.3, available: true },
      { name: "Lavender Syrup pump", price: 0.3, available: true },
      { name: "Mango puree", price: 0.6, available: true },
      { name: "Pumpkin Spice Single Pump", price: 0.3, available: true },
      { name: "Pure Cane Single pump", price: 0.3, available: true },
      { name: "Seasonal Syrup Pump (Disabled)", price: 0.6, available: false },
      { name: "Strawberry Puree", price: 0.6, available: true },
      { name: "Strawberry Syrup Pump", price: 0.3, available: true },
      { name: "SUGAR FREE Vanilla Single Pump", price: 0.3, available: true },
      { name: "Tiramisu Single Pump", price: 0.5, available: true },
      { name: "Toasted Marshmellow Pump", price: 0.3, available: true },
      { name: "Ube Single Pump", price: 0.5, available: true },
      { name: "Vanilla Single Pump", price: 0.3, available: true },
      { name: "White Chocolate Sauce", price: 0.6, available: true },
    ],
  },
  {
    name: "Coffee Toppings",
    description: "Add dry toppings to your drink (cinnamon or cocoa).",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 2,
    options: [
      { name: "Cinnamon Powder", price: 0, available: true },
      { name: "Cocoa Powder", price: 0, available: true },
    ],
  },
  {
    name: "Whipped Cream",
    displayName: "Whipped cream (add-on)",
    description:
      "Extra whipped cream (+$0.75). Iced mocha latte already includes whipped cream—use this only if you want an additional serving.",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 1,
    options: [
      { name: "Add whipped cream (+$0.75)", price: 0.75, available: true },
    ],
  },
  {
    name: "Extra Single Shots (Hot)",
    description: "Add extra espresso shots ($1.25 per shot)",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 5,
    options: [
      { name: "Extra Single Shot", price: 1.25, available: true },
    ],
  },
  {
    name: "Extra Single Shots (Iced)",
    description: "Add extra espresso shots ($1.25 per shot)",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 5,
    options: [
      { name: "Extra Single Shot", price: 1.25, available: true },
    ],
  },
  {
    name: "Extra Single Shots (Smoothie)",
    description: "Add espresso shots to your smoothie ($1.25 per shot, max 2)",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 2,
    options: [
      { name: "Extra Single Shot", price: 1.25, available: true },
    ],
  },
  {
    name: "Milk Choice",
    description:
      "Whole, 2%, skim, or half & half at no charge. Heavy cream +$0.60. Almond, oat, or soy +$0.80.",
    type: "single",
    required: true,
    options: [
      { name: "Whole Milk", price: 0, available: true },
      { name: "2% Milk", price: 0, available: true },
      { name: "Skim Milk", price: 0, available: true },
      { name: "half & half", price: 0, available: true },
      { name: "No Milk", price: 0, available: true },
      { name: "Heavy Cream", price: 0.6, available: true },
      { name: "Oat Milk", price: 0.8, available: true },
      { name: "Soy Milk", price: 0.8, available: true },
      { name: "Almond Milk", price: 0.8, available: true },
    ],
  },
  {
    name: "Milk Choice (Smoothies)",
    description:
      "Whole, 2%, skim, or half & half at no charge. Heavy cream +$0.60. Almond, oat, or soy +$0.80.",
    type: "single",
    required: true,
    options: [
      { name: "Whole Milk", price: 0, available: true },
      { name: "2% Milk", price: 0, available: true },
      { name: "Skim Milk", price: 0, available: true },
      { name: "half & half", price: 0, available: true },
      { name: "No Milk", price: 0, available: true },
      { name: "Heavy Cream", price: 0.6, available: true },
      { name: "Almond Milk", price: 0.8, available: true },
      { name: "Oat Milk", price: 0.8, available: true },
      { name: "Soy Milk", price: 0.8, available: true },
    ],
  },
  {
    name: "Ice Level",
    description: "Select your ice preference (optional)",
    type: "single",
    required: false,
    options: [
      { name: "No Ice", price: 0, available: true },
      { name: "Light Ice", price: 0, available: true },
      { name: "Medium Ice", price: 0, available: true },
      { name: "Extra Ice", price: 0, available: true },
    ],
  },
  {
    name: "Cold Foam",
    description: "Add cold foam (matches Clover modifier pricing)",
    type: "single",
    required: false,
    options: [
      { name: "Blueberry Cold Foam", price: 1, available: true },
      { name: "Mango Cold Foam", price: 1, available: true },
      { name: "Matcha Cold Foam", price: 1.25, available: true },
      { name: "Strawberry Cold Foam", price: 1, available: true },
      { name: "Vanilla Cold Foam (White)", price: 0.75, available: true },
    ],
  },
  // Build-your-own oatmeal modifier groups (matches POS inventory-export-v2)
  {
    name: "Base",
    description: "Choose your base (required)",
    type: "single",
    required: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { name: "Chia Seeds Pudding", price: 0, available: true },
      { name: "Yogurt", price: 0, available: true },
      { name: "Chia Seeds Pudding & Yogurt", price: 0, available: true },
    ],
  },
  {
    name: "Wild Vegan Base",
    description: "Chia seed pudding made with plant-based almond milk (vegan)",
    type: "single",
    required: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { name: "Chia Seeds Pudding", price: 0, available: true },
    ],
  },
  {
    name: "Bowl Size",
    description: "Choose your bowl size (required). Medium is +$1.",
    type: "single",
    required: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { name: "Small (12oz)", price: 0, available: true },
      { name: "Medium (16oz)", price: 1, available: true },
    ],
  },
  {
    name: "Toppings",
    description: "Choose at least 3 dried toppings (up to 8)",
    type: "multiple",
    required: true,
    minSelections: 3,
    maxSelections: 8,
    options: [
      { name: "Sliced almonds", price: 0, available: true },
      { name: "Chopped walnuts", price: 0, available: true },
      { name: "Chopped pecans", price: 0, available: true },
      { name: "Dried cranberries", price: 0, available: true },
      { name: "Raisins", price: 0, available: true },
      { name: "Coconut flakes", price: 0, available: true },
      { name: "Sunflower Seeds", price: 0, available: true },
      { name: "Granola", price: 0, available: true },
      { name: "Peanut Crunch", price: 0, available: true },
    ],
  },
  {
    name: "Drizzels",
    description: "Choose up to 2 drizzles (optional)",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 2,
    options: [
      { name: "Peanut Butter", price: 0, available: true },
      { name: "Honey", price: 0, available: true },
      { name: "Chocolate", price: 0, available: true },
    ],
  },
  {
    name: "Fruit Toppings",
    description: "Choose at least 2 fresh fruits",
    type: "multiple",
    required: true,
    minSelections: 2,
    maxSelections: 2,
    options: [
      { name: "Strawberries", price: 0, available: true },
      { name: "Blueberries", price: 0, available: true },
      { name: "Bananas", price: 0, available: true },
    ],
  },
  {
    name: "Extra Add-Ons",
    description: "Extra base $2, extra dry/fruit $0.75, Peanut Butter/Honey $0.50, Chocolate $0.75",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 17,
    options: [
      { name: "Chia Seeds Pudding", price: 2, available: true },
      { name: "Yogurt", price: 2, available: true },
      { name: "Sliced almonds", price: 0.75, available: true },
      { name: "Chopped walnuts", price: 0.75, available: true },
      { name: "Chopped pecans", price: 0.75, available: true },
      { name: "Dried cranberries", price: 0.75, available: true },
      { name: "Raisins", price: 0.75, available: true },
      { name: "Coconut flakes", price: 0.75, available: true },
      { name: "Sunflower Seeds", price: 0.75, available: true },
      { name: "Granola", price: 0.75, available: true },
      { name: "Peanut Crunch", price: 0.75, available: true },
      { name: "Strawberries", price: 0.75, available: true },
      { name: "Blueberries", price: 0.75, available: true },
      { name: "Bananas", price: 0.75, available: true },
      { name: "Peanut Butter", price: 0.5, available: true },
      { name: "Honey", price: 0.5, available: true },
      { name: "Chocolate", price: 0.75, available: true },
    ],
  },
  {
    name: "Smoothie Add-Ons",
    description: "Add extra ingredients to your smoothie",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 10,
    options: [
      { name: "Avocado (1/4)", price: 0.75, available: true },
      { name: "Bananas", price: 0.75, available: true },
      { name: "Blueberries", price: 0.75, available: true },
      { name: "Chia Seed Pudding", price: 1, available: true },
      { name: "Chia Seeds", price: 0.5, available: true },
      { name: "Coconut syrup", price: 0.75, available: true },
      { name: "Guava Juice", price: 0.75, available: true },
      { name: "Honey", price: 0.75, available: true },
      { name: "Kale", price: 0.75, available: true },
      { name: "Mango", price: 0.75, available: true },
      { name: "Orange Juice", price: 0.75, available: true },
      { name: "Peanut Butter", price: 0.75, available: true },
      { name: "Pineapples", price: 0.75, available: true },
      { name: "Raspberries", price: 0.75, available: true },
      { name: "Spinach", price: 0.75, available: true },
      { name: "Strawberries", price: 0.75, available: true },
      { name: "Yogurt (Vanilla non-fat)", price: 0.75, available: true },
    ],
  },
  {
    name: "Yogurt Choice",
    description: "Select your yogurt preference",
    type: "single",
    required: true, // Required based on "Yes" in your data
    options: [
      { name: "Regular Yogurt", price: 0, available: true },
      { name: "Dairy-Free Yogurt", price: 0.5, available: true },
      { name: "Non-Fat Yogurt", price: 0.5, available: true },
    ],
  },
  {
    name: "Warmed",
    description: "Would you like your pastry warmed?",
    type: "single",
    required: false,
    options: [
      { name: "Not Warmed", price: 0, available: true },
      { name: "Warmed", price: 0, available: true },
    ],
  },
  {
    name: "Toasted",
    description: "Would you like your bagel toasted?",
    type: "single",
    required: false,
    options: [
      { name: "Not Toasted", price: 0, available: true },
      { name: "Toasted", price: 0, available: true },
    ],
  },
  {
    name: "Tea Selection",
    description: "Select your tea type",
    type: "single",
    required: true,
    options: [
      { name: "English Breakfast", price: 0, available: true },
      { name: "Earl Grey", price: 0, available: true },
      { name: "Green Tea", price: 0, available: true },
      { name: "Chamomile Tea", price: 0, available: true },
    ],
  },
];
