// Modifier Groups Seed Data
// Based on Clover POS export analysis - Updated with exact options and pricing

export const modifierGroups = [
  {
    name: "Shot Preference",
    description: "Choose your espresso shot preference",
    type: "single",
    required: false,
    options: [
      { name: "Single Shot (instead of double)", price: 0, available: true },
    ],
  },
  {
    name: "Cup Size (12-16)",
    description: "Select your cup size",
    type: "single",
    required: true,
    options: [
      { name: "Small (12oz)", price: 0, available: true },
      { name: "Medium (16oz)", price: 0.5, available: true },
      { name: "Large (20oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Cup Size (16-20)",
    description: "Select your cup size",
    type: "single",
    required: true,
    options: [
      { name: "Medium (16oz)", price: 0, available: true },
      { name: "Large (20oz)", price: 0.75, available: true },
      { name: "Small (12oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Cold Brew Cup Size (16-20)",
    displayName: "Cup Size (16-20)",
    description: "Select your cup size",
    type: "single",
    required: true,
    options: [
      { name: "Medium (16oz)", price: 0, available: true },
      { name: "Large (20oz)", price: 0.25, available: true },
      { name: "Small (12oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Hot Cup Size",
    description: "Select your hot cup size",
    type: "single",
    required: true,
    options: [
      { name: "Small (12oz)", price: 0, available: true },
      { name: "Medium (16oz)", price: 0.5, available: true },
      { name: "Large (20oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Cold Cup Size",
    description: "Select your cold cup size",
    type: "single",
    required: true,
    options: [
      { name: "Medium (16oz)", price: 0, available: true },
      { name: "Large (20oz)", price: 0.75, available: true },
      { name: "Small (12oz) (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Syrup Pumps (+$0.20 each)",
    description: "Add flavored syrup pumps",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 3, // Updated to match available options (Vanilla, Caramel, Hazelnut)
    options: [
      { name: "Vanilla Syrup Pump", price: 0.2, available: true },
      { name: "Caramel Syrup Pump", price: 0.2, available: true },
      { name: "Hazelnut Syrup Pump", price: 0.2, available: true },
      { name: "Mocha Syrup Pump (Disabled)", price: 0.2, available: false },
      { name: "Pumpkin Spice Syrup Pump (Disabled)", price: 0.2, available: false },
      { name: "French Vanilla Syrup Pump (Disabled)", price: 0.2, available: false },
      { name: "Cinnamon Syrup Pump (Disabled)", price: 0.2, available: false },
      { name: "Seasonal Syrup Pump (Disabled)", price: 0.2, available: false },
    ],
  },
  {
    name: "Coffee Toppings",
    description: "Add toppings to your coffee",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 3, // Updated to match available options (Whipped Cream, Cinnamon Powder, Cocoa Powder)
    options: [
      { name: "Whipped Cream (+$0.50)", price: 0.5, available: true },
      { name: "Cinnamon Powder", price: 0, available: true },
      { name: "Cocoa Powder", price: 0, available: true },
    ],
  },
  {
    name: "Extra Single Shots (Hot)",
    description: "Add extra espresso shots ($1.25 per shot)",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 5,
    options: [
      { name: "Extra Single Shot", price: 1.25, available: true },
    ],
  },
  {
    name: "Extra Single Shots (Iced)",
    description: "Add extra espresso shots ($1.25 per shot)",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 5,
    options: [
      { name: "Extra Single Shot", price: 1.25, available: true },
    ],
  },
  {
    name: "Milk Choice",
    description: "Select your milk preference",
    type: "single",
    required: true,
    options: [
      { name: "2% Milk", price: 0, available: true },
      { name: "Oat Milk", price: 0.5, available: true },
      { name: "No Milk", price: 0, available: true },
      { name: "Almond Milk", price: 0.5, available: true },
      { name: "Whole Milk (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Milk Choice (Smoothies)",
    description: "Select your milk preference",
    type: "single",
    required: true,
    options: [
      { name: "Almond Milk", price: 0, available: true },
      { name: "2% Milk", price: 0, available: true },
      { name: "Oat Milk", price: 0.5, available: true },
      { name: "No Milk", price: 0, available: true },
      { name: "Whole Milk (Disabled)", price: 0, available: false },
    ],
  },
  {
    name: "Ice Level",
    description: "Select your ice preference (optional)",
    type: "single",
    required: false,
    options: [
      { name: "No Ice", price: 0, available: true },
      { name: "Light Ice", price: 0, available: true },
      { name: "Medium Ice", price: 0, available: true },
      { name: "Extra Ice", price: 0, available: true },
    ],
  },
  // Build-your-own oatmeal modifier groups (matches POS inventory-export-v2)
  {
    name: "Oatmeal Base",
    description: "Choose your base (required)",
    type: "single",
    required: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { name: "Oatmeal", price: 0, available: true },
      { name: "Chia Seeds Pudding", price: 0, available: true },
      { name: "Yogurt", price: 0, available: true },
      { name: "Oatmeal & Yogurt", price: 0, available: true },
      { name: "Oatmeal & Chia Seeds Pudding", price: 0, available: true },
      { name: "Chia Seeds Pudding & Yogurt", price: 0, available: true },
    ],
  },
  {
    name: "Wild Vegan Base",
    description: "Chia seed pudding made with plant-based almond milk (vegan)",
    type: "single",
    required: true,
    minSelections: 1,
    maxSelections: 1,
    options: [
      { name: "Chia Seeds Pudding", price: 0, available: true },
    ],
  },
  {
    name: "Oatmeal Dried Toppings",
    description: "Choose up to 8 dried toppings",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 8,
    options: [
      { name: "Sliced almonds", price: 0, available: true },
      { name: "Chopped walnuts", price: 0, available: true },
      { name: "Chopped pecans", price: 0, available: true },
      { name: "Dried cranberries", price: 0, available: true },
      { name: "Raisins", price: 0, available: true },
      { name: "Coconut flakes", price: 0, available: true },
      { name: "Sunflower Seeds", price: 0, available: true },
      { name: "Granola", price: 0, available: true },
    ],
  },
  {
    name: "Oatmeal Drizzels",
    description: "Choose up to 2 drizzles",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 2,
    options: [
      { name: "Peanut Butter", price: 0, available: true },
      { name: "Honey", price: 0, available: true },
    ],
  },
  {
    name: "Oatmeal Fruit Toppings",
    description: "Choose up to 2 fresh fruits",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 2,
    options: [
      { name: "Strawberries", price: 0, available: true },
      { name: "Blueberries", price: 0, available: true },
      { name: "Bananas", price: 0, available: true },
      { name: "Rasberries", price: 0, available: true },
    ],
  },
  {
    name: "Oatmeal EXTRA Add-Ons",
    description: "Extra base $2, extra dry/fruit $0.75, Peanut Butter/Honey $0.50",
    type: "multiple",
    required: false,
    minSelections: 0,
    maxSelections: 17,
    options: [
      { name: "Oatmeal", price: 2, available: true },
      { name: "Chia Seeds Pudding", price: 2, available: true },
      { name: "Yogurt", price: 2, available: true },
      { name: "Sliced almonds", price: 0.75, available: true },
      { name: "Chopped walnuts", price: 0.75, available: true },
      { name: "Chopped pecans", price: 0.75, available: true },
      { name: "Dried cranberries", price: 0.75, available: true },
      { name: "Raisins", price: 0.75, available: true },
      { name: "Coconut flakes", price: 0.75, available: true },
      { name: "Sunflower Seeds", price: 0.75, available: true },
      { name: "Granola", price: 0.75, available: true },
      { name: "Strawberries", price: 0.75, available: true },
      { name: "Blueberries", price: 0.75, available: true },
      { name: "Bananas", price: 0.75, available: true },
      { name: "Rasberries", price: 0.75, available: true },
      { name: "Peanut Butter", price: 0.5, available: true },
      { name: "Honey", price: 0.5, available: true },
    ],
  },
  {
    name: "Smoothie Add-Ons",
    description: "Add extra ingredients to your smoothie",
    type: "multiple",
    required: false, // Add-ons are typically optional, even if marked "Yes" in Clover
    minSelections: 0,
    maxSelections: 5, // Updated to match available options (Chia Seeds, Peanut Butter, Almonds, Cinnamon, Honey)
    options: [
      { name: "Chia Seeds", price: 0.25, available: true },
      { name: "Peanut Butter", price: 0.5, available: true },
      { name: "Almonds", price: 0.25, available: true },
      { name: "Cinnamon", price: 0.25, available: true },
      { name: "Honey", price: 0.5, available: true },
    ],
  },
  {
    name: "Yogurt Choice",
    description: "Select your yogurt preference",
    type: "single",
    required: true, // Required based on "Yes" in your data
    options: [
      { name: "Regular Yogurt", price: 0, available: true },
      { name: "Dairy-Free Yogurt", price: 0.5, available: true },
      { name: "Non-Fat Yogurt", price: 0.5, available: true },
    ],
  },
  {
    name: "Warmed",
    description: "Would you like your pastry warmed?",
    type: "single",
    required: false,
    options: [
      { name: "Not Warmed", price: 0, available: true },
      { name: "Warmed", price: 0, available: true },
    ],
  },
  {
    name: "Toasted",
    description: "Would you like your bagel toasted?",
    type: "single",
    required: false,
    options: [
      { name: "Not Toasted", price: 0, available: true },
      { name: "Toasted", price: 0, available: true },
    ],
  },
  {
    name: "Tea Selection",
    description: "Select your tea type",
    type: "single",
    required: true,
    options: [
      { name: "English Breakfast", price: 0, available: true },
      { name: "Earl Grey", price: 0, available: true },
      { name: "Green Tea", price: 0, available: true },
      { name: "Chamomile Tea", price: 0, available: true },
    ],
  },
];
