/**
 * Menu Items Seed Data - Updated from Clover CSV Export
 * This file contains the exact menu items, prices, descriptions, and modifier group mappings
 * from the Clover POS system.
 */

export const menuItemsFromCSV = [
  // Coffee & Espresso (Espresso Bar)
  {
    name: "Americano",
    description: "Espresso shot filled with hot water for a smooth finish.",
    price: 3.6,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/AmericanoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (12-16)",
      "Extra Single Shots (Hot)",
    ],
  },
  {
    name: "Cappuccino",
    description: "Espresso with equal parts steamed milk and foam.",
    price: 4.55,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "foam"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/CappuccinoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Cup Size (12-16)",
      "Extra Single Shots (Hot)",
      "Milk Choice",
    ],
  },
  {
    name: "Doppio",
    description: "A bold double shot of espresso.",
    price: 3.05,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/DoppioLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Shot Preference", "Extra Single Shots (Hot)"],
  },
  {
    name: "Espresso",
    description: "1 oz espresso shot made with freshly roasted beans.",
    price: 2.85,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/EspressoLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Shot Preference", "Extra Single Shots (Hot)"],
  },
  {
    name: "Flat White",
    description: "Espresso with velvety, lightly textured milk.",
    price: 5.1,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "milk"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/LatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Cup Size (12-16)",
      "Extra Single Shots (Hot)",
      "Milk Choice",
    ],
  },
  {
    name: "Latte",
    description: "Espresso with steamed milk and a light milk crema.",
    price: 4.55,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "milk"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/LatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (12-16)",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Milk Choice",
      "Extra Single Shots (Hot)",
    ],
  },
  {
    name: "Mocha",
    description: "Espresso blended with chocolate and steamed milk.",
    price: 5.15,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "chocolate"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/MochaLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Cup Size (12-16)",
      "Extra Single Shots (Hot)",
      "Milk Choice",
    ],
  },
  {
    name: "Espresso Macchiato",
    description: "Espresso marked with a small amount of foam.",
    price: 5.15,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso"],
    allergens: [],
    image: "/images/menu/Coffee/EspressoMacchiatoLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Shot Preference", "Extra Single Shots (Hot)"],
  },
  {
    name: "Caramel Macchiato",
    description: "Layered espresso and milk with caramel.",
    price: 5.6,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "espresso", "caramel"],
    allergens: ["Dairy"],
    image: "",
    available: false,
    active: false,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (12-16)",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Milk Choice",
      "Extra Single Shots (Hot)",
    ],
  },
  {
    name: "Filtered Coffee",
    description: "Fresh filtered coffee. Select your cup size.",
    price: 2.55,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["hot", "coffee"],
    allergens: [],
    image: "/images/menu/Coffee/RegularCoffeeLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Cup Size (12-16)"],
  },

  // Cold Coffee
  {
    name: "Cold Brew",
    description: "Slow-steeped cold brew for a smooth, rich taste.",
    price: 4.65,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "coffee", "cold"],
    allergens: [],
    image: "/images/menu/Coffee/IcedAmericanoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Brew Cup Size (16-20)",
      "Ice Level",
      "Milk Choice",
      "Syrup Pumps (+$0.20 each)",
    ],
  },
  {
    name: "Iced Americano",
    description: "Espresso and cold water served over ice.",
    price: 3.95,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: [],
    image: "/images/menu/Coffee/IcedAmericanoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Ice Level",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Iced Cappuccino",
    description: "Chilled espresso with milk and foam over ice.",
    price: 4.85,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedCappuccinoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Iced Caramel Macchiato",
    description: "Layered espresso and milk served over ice.",
    price: 5.6,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedCaramelMacchiatoLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Iced Latte",
    description: "Espresso with cold milk poured over ice.",
    price: 4.65,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Iced Flat White",
    description: "Flat white served over ice.",
    price: 4.85,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedFlatWhiteLand.png",
    available: true,
    active: false,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Extra Single Shots (Iced)",
    ],
  },
  {
    name: "Iced Mocha",
    description: "Mocha served over ice.",
    price: 5.85,
    currency: "USD",
    section: "Coffee & Espresso",
    tags: ["iced", "espresso", "chocolate", "cold"],
    allergens: ["Dairy"],
    image: "/images/menu/Coffee/IcedMochaLand.png",
    available: true,
    active: false,
    modifierGroupNames: [
      "Shot Preference",
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.20 each)",
      "Coffee Toppings",
      "Ice Level",
      "Milk Choice",
      "Extra Single Shots (Iced)",
    ],
  },

  // Smoothies
  {
    name: "Green Glow",
    description:
      "Spinach, kale, banana, avocado, chia seeds, almond milk, honey\nAllergens: Tree Nuts",
    price: 7.99,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "green"],
    allergens: ["Tree Nuts"],
    image: "/images/menu/Smoothies/GreenGlowLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Milk Choice (Smoothies)",
      "Smoothie Add-Ons",
      "Yogurt Choice",
    ],
  },
  {
    name: "Berry Boost",
    description:
      "Strawberry, blueberry, raspberry, vanilla yogurt, almond milk\nAllergens: Dairy, tree nuts",
    price: 8.2,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "berry"],
    allergens: ["Dairy", "Tree Nuts"],
    image: "/images/menu/Smoothies/BerryBoostLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Milk Choice (Smoothies)",
      "Smoothie Add-Ons",
      "Yogurt Choice",
    ],
  },
  {
    name: "Tropical Bliss",
    description:
      "Mango, pineapple, banana, orange juice, almond milk, fresh lime, Coconut Cream\nAllergens: Coconut, Tree Nuts",
    price: 7.5,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "tropical"],
    allergens: ["Coconut", "Tree Nuts"],
    image: "/images/menu/Smoothies/TropicalBlissLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Smoothie Add-Ons", "Yogurt Choice"],
  },
  {
    name: "Nutty Banana Bliss",
    description:
      "Banana, peanut butter, chia seeds, almonds, cinnamon, and almond milk\nAllergens: Peanuts, Tree Nuts",
    price: 7.5,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "nutty"],
    allergens: ["Peanuts", "Tree Nuts"],
    image: "/images/menu/Smoothies/NuttyBananaBlissLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Milk Choice (Smoothies)",
      "Smoothie Add-Ons",
      "Yogurt Choice",
    ],
  },
  {
    name: "Guava Cream",
    description: "Guava, yogurt, avocado, fresh lime\nAllergens: Dairy",
    price: 7.75,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "tropical", "guava"],
    allergens: ["Dairy"],
    image: "/images/menu/Smoothies/GuavaCreamLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Milk Choice (Smoothies)",
      "Smoothie Add-Ons",
      "Yogurt Choice",
    ],
  },
  {
    name: "Dirty Banana Smoothie",
    description:
      "Espresso, Banana, Yogurt Chocolate Sauce, Honey\nAllergens: Dairy",
    price: 7.75,
    currency: "USD",
    section: "Smoothies (Organic & Fresh)",
    tags: ["smoothie", "organic", "fresh", "espresso", "banana"],
    allergens: ["Dairy"],
    image: "/images/menu/Smoothies/DirtyBananaSmoothieLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Shot Preference",
      "Milk Choice (Smoothies)",
      "Smoothie Add-Ons",
      "Yogurt Choice",
    ],
  },

  // Wild Bowl (build-your-own bowl; matches POS Wild Bowl)
  {
    name: "Build Your Own Bowl",
    description:
      "Build your own bowl. Required: choose a base (Oats, Chia pudding, Yogurt), 2 Choice of fresh Fruits and Any dry toppings, and Any Drizzles",
    price: 9.99,
    currency: "USD",
    section: "Wild Bowl",
    tags: ["bowl", "custom", "healthy", "breakfast", "build your own"],
    allergens: [],
    image: "/images/menu/Oatmeals/NutFree.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Oatmeal Base",
      "Oatmeal Dried Toppings",
      "Oatmeal Drizzels",
      "Oatmeal Fruit Toppings",
      "Oatmeal EXTRA Add-Ons",
    ],
  },
  {
    name: "Wild Vegan",
    description:
      "Vegan build-your-own bowl. Base: chia seed pudding (plant-based almond milk). Same rules as Wild Bowl: 2 choice of fresh fruits, any dry toppings, and any drizzles.",
    price: 9.99,
    currency: "USD",
    section: "Wild Bowl",
    tags: ["bowl", "custom", "healthy", "breakfast", "vegan"],
    allergens: [],
    image: "/images/menu/Oatmeals/NutFree.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Wild Vegan Base",
      "Oatmeal Dried Toppings",
      "Oatmeal Drizzels",
      "Oatmeal Fruit Toppings",
      "Oatmeal EXTRA Add-Ons",
    ],
  },

  // Bakery & Pastries
  {
    name: "Chocolate Muffin",
    description: "Soft muffin packed with chocolate chips.",
    price: 3.65,
    currency: "USD",
    section: "Bakery & Pastries",
    tags: ["bakery", "muffin", "chocolate"],
    allergens: ["Gluten", "Dairy"],
    image: "/images/menu/Bakery/ChocolateMuffinLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Blue Berry Muffin",
    description: "Soft muffin packed with mixed berries.",
    price: 3.65,
    currency: "USD",
    section: "Bakery & Pastries",
    tags: ["bakery", "muffin", "berry"],
    allergens: ["Gluten", "Dairy"],
    image: "/images/menu/Bakery/BlueBerryMuffinLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Banana Blue Berry Bread",
    description: "Moist banana bread with fresh blueberries.",
    price: 3.75,
    currency: "USD",
    section: "Bakery & Pastries",
    tags: ["bakery", "bread", "banana", "berry"],
    allergens: ["Gluten", "Dairy"],
    image: "/images/menu/Bakery/BlueBerryBananaBreadLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Almond Croissant",
    description: "Flaky croissant with almond filling and topping.",
    price: 4.25,
    currency: "USD",
    section: "Bakery & Pastries",
    tags: ["bakery", "croissant", "almond"],
    allergens: ["Gluten", "Dairy", "Tree Nuts"],
    image: "/images/menu/Bakery/AlmondCroissantLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Butter Croissant",
    description: "Buttery, flaky classic croissant.",
    price: 3.75,
    currency: "USD",
    section: "Bakery & Pastries",
    tags: ["bakery", "croissant"],
    allergens: ["Gluten", "Dairy"],
    image: "/images/menu/Bakery/ButterCroissantLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Warmed"],
  },
  {
    name: "Plain Bagel",
    description: "Freshly baked classic bagel.",
    price: 3.25,
    currency: "USD",
    section: "Bakery & Pastries",
    tags: ["bakery", "bagel"],
    allergens: ["Gluten"],
    image: "/images/menu/Bakery/PlainBagelLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Toasted"],
  },
  {
    name: "Everything Bagel",
    description:
      "Freshly baked bagel topped with sesame seeds, poppy seeds, onion, and garlic.",
    price: 3.45,
    currency: "USD",
    section: "Bakery & Pastries",
    tags: ["bakery", "bagel"],
    allergens: ["Gluten"],
    image: "/images/menu/Bakery/EverythingBagelLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Toasted"],
  },
  {
    name: "Wheat Bagel",
    description: "Freshly baked whole wheat bagel.",
    price: 3.45,
    currency: "USD",
    section: "Bakery & Pastries",
    tags: ["bakery", "bagel"],
    allergens: ["Gluten"],
    image: "/images/menu/Bakery/WheatBagelLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Toasted"],
  },

  // Tea
  {
    name: "Assorted Tea",
    description: "Choose from an assortion of teas",
    price: 3.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot"],
    allergens: [],
    image: "/images/menu/Favorites/AssortedTeasLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Tea Selection"],
  },
  {
    name: "Iced Tea",
    description: "Fresh-brewed tea served over ice.",
    price: 3.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced"],
    allergens: [],
    image: "/images/menu/Favorites/IcedTeaLand.png",
    available: true,
    active: true,
    modifierGroupNames: ["Tea Selection", "Cold Cup Size", "Ice Level"],
  },
  {
    name: "Chai Latte (Hot)",
    description: "Spiced chai blended with steamed milk.",
    price: 5.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot", "spiced"],
    allergens: [],
    image: "/images/menu/Favorites/ChaiLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Syrup Pumps (+$0.20 each)",
      "Cup Size (12-16)",
      "Milk Choice",
    ],
  },
  {
    name: "Matcha Latte (Hot)",
    description: "Matcha blended with steamed milk",
    price: 5.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "hot", "matcha"],
    allergens: [],
    image: "/images/menu/Favorites/MatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Hot Cup Size",
      "Milk Choice",
      "Syrup Pumps (+$0.20 each)",
    ],
  },
  {
    name: "Iced Chai Latte",
    description: "Spiced chai tea blended with steamed milk.",
    price: 5.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "spiced"],
    allergens: [],
    image: "/images/menu/Favorites/IcedChaiLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cup Size (16-20)",
      "Syrup Pumps (+$0.20 each)",
      "Ice Level",
      "Milk Choice",
    ],
  },
  {
    name: "Iced Matcha Latte",
    description: "Matcha blended with milk and shaken over ice",
    price: 5.45,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha"],
    allergens: [],
    image: "/images/menu/Favorites/IcedMatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Cup Size",
      "Syrup Pumps (+$0.20 each)",
      "Milk Choice",
      "Ice Level",
    ],
  },
  {
    name: "Iced Strawberry Matcha Latte",
    description: "Matcha with strawberry and milk, shaken over ice.",
    price: 6.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "strawberry"],
    allergens: ["Dairy"],
    image: "/images/menu/Favorites/StrawberryMatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Brew Cup Size (16-20)",
      "Syrup Pumps (+$0.20 each)",
      "Milk Choice",
      "Ice Level",
    ],
  },
  {
    name: "Iced Blueberry Matcha Latte",
    description: "Matcha with blueberry and milk, shaken over ice.",
    price: 6.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "blueberry"],
    allergens: ["Dairy"],
    image: "/images/menu/Favorites/BlueberryMatchaLatteLand.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Brew Cup Size (16-20)",
      "Syrup Pumps (+$0.20 each)",
      "Milk Choice",
      "Ice Level",
    ],
  },
  {
    name: "Iced Mango Matcha Latte",
    description: "Matcha with mango and milk, shaken over ice.",
    price: 6.25,
    currency: "USD",
    section: "Tea",
    tags: ["tea", "iced", "matcha", "mango"],
    allergens: ["Dairy"],
    image: "/images/menu/Favorites/MangoMatchaLatte.png",
    available: true,
    active: true,
    modifierGroupNames: [
      "Cold Brew Cup Size (16-20)",
      "Syrup Pumps (+$0.20 each)",
      "Milk Choice",
      "Ice Level",
    ],
  },
];
